/**
 * Per-optimization human-readable texts (ES/EN).
 * Single source of truth consumed by the optimization API details
 * (optimization-details.ts) and the UI catalog (FullOptimizationPanel).
 *
 * Fields per entry:
 *  - desc: short card description
 *  - isIt: what the Windows feature actually is
 *  - does: what applying the optimization concretely does
 *  - applies: which components/areas are affected
 */

export interface OptimizationTexts {
  descEs: string;
  descEn: string;
  isItEs: string;
  isItEn: string;
  doesEs: string;
  doesEn: string;
  appliesEs: string;
  appliesEn: string;
}

const t = (
  descEs: string, descEn: string,
  isItEs: string, isItEn: string,
  doesEs: string, doesEn: string,
  appliesEs: string, appliesEn: string,
): OptimizationTexts => ({ descEs, descEn, isItEs, isItEn, doesEs, doesEn, appliesEs, appliesEn });

export const optimizationTexts: Record<string, OptimizationTexts> = {
  // ─── SYSTEM ───────────────────────────────────────────────────────────────
  'disable-telemetry': t(
    'Bloquea la telemetría de diagnóstico y el servicio de seguimiento DiagTrack.',
    'Blocks diagnostic telemetry and the DiagTrack tracking service.',
    'La telemetría es el canal por el que Windows envía datos de uso y diagnóstico a Microsoft; DiagTrack es el servicio que los transporta.',
    'Telemetry is the channel Windows uses to send usage and diagnostic data to Microsoft; DiagTrack is the service that transports it.',
    'Fija la directiva AllowTelemetry en 0 y detiene y deshabilita los servicios DiagTrack y dmwappushservice.',
    'Sets the AllowTelemetry policy to 0 and stops and disables the DiagTrack and dmwappushservice services.',
    'Directiva de diagnóstico de HKLM, servicio DiagTrack y envío de datos en segundo plano.',
    'HKLM diagnostic policy, the DiagTrack service, and background data uploads.',
  ),
  'disable-cortana': t(
    'Desactiva Cortana mediante directiva de grupo.',
    'Disables Cortana via group policy.',
    'Cortana era el asistente de voz integrado de Windows; en versiones modernas solo persiste su integración de búsqueda.',
    'Cortana was the built-in Windows voice assistant; on modern versions only its search integration remains.',
    'Crea la clave de directiva "Windows Search" y fija AllowCortana=0 para que Windows no cargue el asistente.',
    'Creates the "Windows Search" policy key and sets AllowCortana=0 so Windows does not load the assistant.',
    'Directivas de búsqueda de HKLM y procesos de Cortana en segundo plano.',
    'HKLM search policies and background Cortana processes.',
  ),
  'disable-search-indexing': t(
    'Detiene y deshabilita el indexador de búsqueda de Windows (WSearch).',
    'Stops and disables the Windows Search indexer (WSearch).',
    'El indexador construye y mantiene una base de datos de tus archivos para que las búsquedas del menú Inicio sean instantáneas.',
    'The indexer builds and maintains a database of your files so Start-menu searches are instant.',
    'Detiene el servicio WSearch y cambia su inicio a Deshabilitado; las búsquedas pasarán a escanear discos en tiempo real.',
    'Stops the WSearch service and sets its startup to Disabled; searches will scan drives in real time instead.',
    'Disco (E/S constante), servicio WSearch y velocidad del menú de búsqueda.',
    'Disk (constant I/O), the WSearch service, and search-menu speed.',
  ),
  'disable-superfetch': t(
    'Deshabilita Superfetch/SysMain, el precargador de aplicaciones en memoria.',
    'Disables Superfetch/SysMain, the app memory preloader.',
    'SysMain analiza tus patrones de uso y precarga apps frecuentes a RAM; útil en HDD, ruido en SSD.',
    'SysMain learns your usage patterns and preloads frequent apps into RAM; useful on HDDs, mostly noise on SSDs.',
    'Detiene SysMain y lo marca como Deshabilitado para liberar CPU, RAM y E/S de disco.',
    'Stops SysMain and marks it Disabled to free CPU, RAM, and disk I/O.',
    'Servicio SysMain, uso de memoria y actividad de disco al arrancar.',
    'The SysMain service, memory usage, and disk activity at boot.',
  ),
  'disable-print-spooler': t(
    'Desactiva el spooler de impresión (protege también contra PrintNightmare).',
    'Disables the print spooler (also protects against PrintNightmare).',
    'El spooler (Spooler) gestiona la cola de trabajos de impresión de todas las impresoras del equipo.',
    'The spooler manages the print job queue for every printer on the PC.',
    'Detiene el servicio Spooler y lo deja Deshabilitado; no podrás imprimir hasta reactivarlo.',
    'Stops the Spooler service and leaves it Disabled; printing won\u2019t work until you re-enable it.',
    'Servicio Spooler, colas de impresión y drivers de impresora.',
    'The Spooler service, print queues, and printer drivers.',
  ),
  'disable-xbox-gamebar': t(
    'Desactiva Xbox Game Bar y la captura en segundo plano de Game DVR.',
    'Disables Xbox Game Bar and background Game DVR capture.',
    'Game Bar es la superposición de juegos de Windows (Win+G); Game DVR graba clips en segundo plano consumiendo GPU/CPU.',
    'Game Bar is the Windows gaming overlay (Win+G); Game DVR records background clips consuming GPU/CPU.',
    'Escribe AppCaptureEnabled=0 y GameDVR_Enabled=0 en el registro para apagar la grabación y la superposición.',
    'Writes AppCaptureEnabled=0 and GameDVR_Enabled=0 to turn off recording and the overlay.',
    'Registro de GameDVR/GameConfigStore, superposición Win+G y capturas de juego.',
    'GameDVR/GameConfigStore registry, the Win+G overlay, and game captures.',
  ),
  'optimize-startup': t(
    'Guía para revisar programas de inicio en el Administrador de tareas.',
    'Guide to review startup programs in Task Manager.',
    'Los programas de inicio se ejecutan al arrancar Windows y prolongan el tiempo hasta estar listo.',
    'Startup programs run when Windows boots and extend time-to-ready.',
    'Abre el Administrador de tareas para que decidas tú qué apps deshabilitar; no se deshabilita nada automáticamente.',
    'Opens Task Manager so you choose which apps to disable; nothing is disabled automatically.',
    'Pestaña "Aplicaciones de inicio" del Administrador de tareas.',
    'Task Manager\u2019s "Startup apps" tab.',
  ),
  'clear-temp-files': t(
    'Vacía carpetas TEMP del sistema y usuario, Prefetch y la papelera.',
    'Empties system/user TEMP folders, Prefetch, and the Recycle Bin.',
    'Las carpetas temporales acumulan instaladores, cachés y restos de apps que pueden ocupar varios GB.',
    'Temp folders accumulate installers, caches, and app leftovers that can reach several GB.',
    'Borra el contenido de %TEMP%, C:\\Windows\\Temp y Prefetch, y vacía la papelera; acción irreversible.',
    'Deletes contents of %TEMP%, C:\\Windows\\Temp, and Prefetch, and empties the Recycle Bin; irreversible.',
    '%TEMP%, C:\\Windows\\Temp, C:\\Windows\\Prefetch y Papelera de reciclaje.',
    '%TEMP%, C:\\Windows\\Temp, C:\\Windows\\Prefetch, and the Recycle Bin.',
  ),
  'disable-error-reporting': t(
    'Desactiva Informe de errores de Windows (WerSvc).',
    'Disables Windows Error Reporting (WerSvc).',
    'WER genera informes detallados cuando una app falla y los envía a Microsoft.',
    'WER generates detailed reports when an app crashes and sends them to Microsoft.',
    'Deshabilita el servicio WerSvc para no generar ni enviar esos informes.',
    'Disables the WerSvc service so crash reports are neither generated nor sent.',
    'Servicio WerSvc, cuadros de "dejó de funcionar" y tráfico hacia servidores WER.',
    'WerSvc service, "stopped working" dialogs, and traffic to WER servers.',
  ),
  'disable-delivery-optimization': t(
    'Deshabilita Optimización de distribución (DoSvc), el P2P de Windows Update.',
    'Disables Delivery Optimization (DoSvc), the Windows Update P2P service.',
    'DoSvc descarga actualizaciones y además puede compartirlas con otros PCs (localmente o a Internet).',
    'DoSvc downloads updates and may also share them with other PCs (locally or over the Internet).',
    'Deshabilita el servicio DoSvc; Windows Update pasará a descargar de forma clásica sin compartir subidas.',
    'Disables DoSvc; Windows Update falls back to classic downloads without peer uploads.',
    'Servicio DoSvc, caché de descargas y ancho de banda de subida.',
    'DoSvc service, download cache, and upload bandwidth.',
  ),
  'disable-windows-insider': t(
    'Deshabilita el servicio del Programa Insider (wisvc).',
    'Disables the Windows Insider Program service (wisvc).',
    'wisvc gestiona la suscripción y las compilaciones de vista previa del Programa Insider.',
    'wisvc manages Insider Program enrollment and preview builds.',
    'Deshabilita wisvc si existe en tu instalación; no cambia tu canal de actualizaciones actual.',
    'Disables wisvc if present on your installation; it does not change your current update channel.',
    'Servicio wisvc y telemetría del Programa Insider.',
    'wisvc service and Insider Program telemetry.',
  ),
  'disable-retail-demo': t(
    'Deshabilita el servicio Retail Demo.',
    'Disables the Retail Demo service.',
    'Retail Demo muestra el modo exposición de tiendas; no sirve en un PC doméstico normal.',
    'Retail Demo shows the store display mode; useless on a normal home PC.',
    'Deshabilita RetailDemo si está presente para evitar su proceso en segundo plano.',
    'Disables RetailDemo if present to avoid its background process.',
    'Servicio RetailDemo y cuenta de modo exposición.',
    'RetailDemo service and the demo-mode account.',
  ),

  // ─── NETWORK ──────────────────────────────────────────────────────────────
  'dns-optimization': t(
    'Configura DNS de Cloudflare (1.1.1.1/1.0.0.1) en adaptadores activos.',
    'Sets Cloudflare DNS (1.1.1.1/1.0.0.1) on active adapters.',
    'Cloudflare opera uno de los DNS públicos más rápidos; puede acelerar la resolución frente al DNS de tu operador.',
    'Cloudflare runs one of the fastest public resolvers; it can beat your ISP DNS at name resolution.',
    'Usa Set-DnsClientServerAddress para fijar 1.1.1.1 y 1.0.0.1 en cada adaptador físico activo.',
    'Uses Set-DnsClientServerAddress to set 1.1.1.1 and 1.0.0.1 on every active physical adapter.',
    'Configuración DNS IPv4 de los adaptadores de red activos.',
    'IPv4 DNS configuration of active network adapters.',
  ),
  'winsock-reset': t(
    'Restablece el catálogo Winsock (netsh winsock reset).',
    'Resets the Winsock catalog (netsh winsock reset).',
    'Winsock define cómo las apps acceden a la red; LSP de terceros corruptos rompen la conectividad.',
    'Winsock defines how apps access the network; corrupt third-party LSPs break connectivity.',
    'Reconstruye el catálogo por defecto eliminando LSP de terceros; requiere reiniciar Windows.',
    'Rebuilds the default catalog removing third-party LSPs; requires a Windows restart.',
    'Catálogo Winsock y proveedores de servicios de red instalados.',
    'The Winsock catalog and installed network service providers.',
  ),
  'flush-dns': t(
    'Vacía la caché DNS local (ipconfig /flushdns).',
    'Flushes the local DNS cache (ipconfig /flushdns).',
    'Windows cachea resoluciones DNS; entradas obsoletas provocan errores o visitas a IPs antiguas.',
    'Windows caches DNS lookups; stale entries cause errors or visits to old IPs.',
    'Borra la caché del resolvedor y verifica con Get-DnsClientCache que quede vacía.',
    'Clears the resolver cache and verifies with Get-DnsClientCache that it is empty.',
    'Caché del cliente DNS (Dnscache).',
    'The DNS client cache (Dnscache).',
  ),
  'reset-network': t(
    'Restablece la pila IP/TCP (netsh int ip/tcp reset).',
    'Resets the IP/TCP stack (netsh int ip/tcp reset).',
    'Repara configuraciones TCP/IP corruptas reescribiendo claves de pila y devolviendo adaptadores a DHCP.',
    'Repairs corrupted TCP/IP configurations by rewriting stack keys and returning adapters to defaults.',
    'Ejecuta netsh int ip reset y netsh int tcp reset; tras reiniciar, toda la config de red vuelve a fábrica.',
    'Runs netsh int ip reset and netsh int tcp reset; after a reboot all network config returns to factory state.',
    'Pila TCP/IP, interfaces y ajustes guardados de red (requiere reinicio).',
    'TCP/IP stack, interfaces, and saved network settings (reboot required).',
  ),
  'disable-llmnr': t(
    'Desactiva LLMNR (EnableMulticast=0 vía directiva).',
    'Disables LLMNR (EnableMulticast=0 via policy).',
    'LLMNR resuelve nombres de equipos en la red local por multicast; también es vector clásico de suplantación.',
    'LLMNR resolves local machine names via multicast; it is also a classic spoofing vector.',
    'Crea la directiva DNSClient EnableMulticast=0 para que Windows no consulte ni responda por LLMNR.',
    'Creates the DNSClient EnableMulticast=0 policy so Windows neither queries nor answers LLMNR.',
    'Resolución multicast de nombres en redes locales.',
    'Local-network multicast name resolution.',
  ),
  'disable-network-throttling': t(
    'Quita el límite multimedia de red (NetworkThrottlingIndex=FFFFFFFF).',
    'Removes multimedia network throttling (NetworkThrottlingIndex=FFFFFFFF).',
    'Windows limita 10 paquetes/ms mientras reproduce medios para priorizar audio/vídeo.',
    'Windows caps 10 packets/ms while media plays to prioritize audio/video.',
    'Escribe NetworkThrottlingIndex=0xFFFFFFFF en SystemProfile para eliminar ese límite.',
    'Writes NetworkThrottlingIndex=0xFFFFFFFF under SystemProfile to lift that cap.',
    'Perfil multimedia del sistema y throughput durante reproducción/juego.',
    'System multimedia profile and throughput during playback/gaming.',
  ),
  'optimize-network-power': t(
    'Evita que Windows apague los adaptadores de red para ahorrar energía.',
    'Prevents Windows from powering down network adapters to save energy.',
    'La suspensión selectiva del adaptador causa microcortes y latencia variable, sobre todo en Wi-Fi.',
    'Adapter selective suspend causes micro-dropouts and jittery latency, especially on Wi-Fi.',
    'Pone AllowComputerToTurnOffDevice=Disabled en cada adaptador físico con Set-NetAdapterPowerManagement.',
    'Sets AllowComputerToTurnOffDevice=Disabled on every physical adapter via Set-NetAdapterPowerManagement.',
    'Gestión de energía de adaptadores Ethernet/Wi-Fi físicos.',
    'Power management of physical Ethernet/Wi-Fi adapters.',
  ),

  // ─── INPUT ────────────────────────────────────────────────────────────────
  'mouse-acceleration': t(
    'Desactiva la aceleración del ratón ("Mejorar precisión del puntero").',
    'Turns off mouse acceleration ("Enhance pointer precision").',
    'Con aceleración activa, el cursor se mueve más lejos cuanto más rápido muevas el ratón; mata la puntería 1:1.',
    'With acceleration on, faster hand movement moves the cursor further; it kills 1:1 aiming consistency.',
    'Escribe MouseSpeed=0 y MouseThreshold1/2=0 en Control Panel\\Mouse para movimiento lineal exacto.',
    'Writes MouseSpeed=0 and MouseThreshold1/2=0 under Control Panel\\Mouse for exact linear movement.',
    'Curva de entrada del puntero de Windows (perfil de usuario).',
    'Windows pointer input curve (per-user profile).',
  ),
  'keyboard-rate': t(
    'Máxima velocidad de repetición y mínimo retardo del teclado.',
    'Maximum keyboard repeat rate and minimum repeat delay.',
    'KeyboardDelay (0-3) y KeyboardSpeed (0-31) definen cuánto tarda una tecla en repetirse y a qué ritmo.',
    'KeyboardDelay (0-3) and KeyboardSpeed (0-31) set how long until a key repeats and how fast.',
    'Fija KeyboardDelay=0 y KeyboardSpeed=31: repetición inmediata al máximo ritmo posible.',
    'Sets KeyboardDelay=0 and KeyboardSpeed=31: instant repeat at the maximum rate.',
    'Valores de teclado de Control Panel (aplican tras reiniciar sesión).',
    'Control Panel keyboard values (apply after sign-in restart).',
  ),
  'touchpad-latency': t(
    'Desactiva la pausa táctil al escribir (AAPThreshold=0).',
    'Disables palm-rejection delay while typing (AAPThreshold=0).',
    'Los touchpads precisos pausan brevemente el cursor tras pulsar teclas para evitar toques accidentales de palma.',
    'Precision touchpads briefly freeze the cursor after keystrokes to avoid accidental palm touches.',
    'Escribe AAPThreshold=0 en PrecisionTouchPad para respuesta inmediata del touchpad.',
    'Writes AAPThreshold=0 under PrecisionTouchPad for immediate touchpad response.',
    'Driver Precision Touchpad de Windows (equipos con touchpad compatible).',
    'The Windows Precision Touchpad driver (compatible-laptop only).',
  ),
  'mouse-polling': t(
    'Guía: el polling del ratón se configura en el software del fabricante.',
    'Guide: mouse polling is configured in vendor software.',
    'La tasa de sondeo (125-1000 Hz+) la decide el firmware del ratón, no Windows.',
    'Polling rate (125-1000 Hz+) is decided by mouse firmware, not Windows.',
    'Muestra instrucciones; no modifica nada del sistema.',
    'Shows instructions; changes nothing on the system.',
    'Software del fabricante (GHUB, Synapse…) y firmware USB del ratón.',
    'Vendor software (GHUB, Synapse…) and the mouse\u2019s USB firmware.',
  ),
  'menu-delay': t(
    'Elimina el retardo al abrir menús (MenuShowDelay=0).',
    'Removes menu open delay (MenuShowDelay=0).',
    'Windows espera 400 ms por defecto entre posar el cursor y desplegar un menú.',
    'Windows waits 400 ms by default between hover and menu display.',
    'Escribe MenuShowDelay=0 en Control Panel\\Desktop para despliegue instantáneo.',
    'Writes MenuShowDelay=0 under Control Panel\\Desktop for instant menus.',
    'Menús contextuales y desplegables del escritorio.',
    'Desktop context and dropdown menus.',
  ),
  'inactive-window-scroll': t(
    'Desactiva el scroll sobre ventanas inactivas (MouseWheelRouting=0).',
    'Disables scrolling inactive windows (MouseWheelRouting=0).',
    'Desde Win10 la rueda hace scroll en la ventana bajo el cursor aunque no tenga foco.',
    'Since Win10 the wheel scrolls the window under the cursor even without focus.',
    'Fija MouseWheelRouting=0 para que la rueda solo actúe en la ventana activa.',
    'Sets MouseWheelRouting=0 so the wheel only acts on the focused window.',
    'Comportamiento de la rueda del ratón en el escritorio.',
    'Mouse-wheel behavior on the desktop.',
  ),
  'disable-sticky-keys': t(
    'Desactiva el atajo de Teclas especiales (Shift x5).',
    'Disables the Sticky Keys shortcut (5x Shift).',
    'Pulsar Shift cinco veces abre el diálogo de Teclas especiales e interrumpe el juego.',
    'Pressing Shift five times pops the Sticky Keys dialog and interrupts your game.',
    'Escribe Flags=506 en Accessibility\\StickyKeys: sin aviso ni activación por atajo.',
    'Writes Flags=506 under Accessibility\\StickyKeys: no prompt, no shortcut activation.',
    'Accesibilidad de teclado del perfil de usuario.',
    'Per-user keyboard accessibility settings.',
  ),
  'disable-usb-suspend': t(
    'Desactiva la suspensión selectiva USB en corriente.',
    'Disables USB selective suspend on AC power.',
    'La suspensión selectiva apaga puertos USB inactivos; en ratones/teclados causa despertares lentos.',
    'Selective suspend powers down idle USB ports; on mice/keyboards it causes slow wake-ups.',
    'powercfg SUB_USB USBSELECTIVE=0 y reactiva el plan para aplicar al instante.',
    'Sets powercfg SUB_USB USBSELECTIVE=0 and reapplies the plan instantly.',
    'Plan de energía activo y administración de energía de puertos USB.',
    'Active power plan and USB port power management.',
  ),
  'timer-resolution-0-5ms': t(
    'Solicita al kernel la resolución mínima de temporizador (0,5 ms) durante la sesión.',
    'Requests the kernel\u2019s lowest timer resolution (0.5 ms) for this session.',
    'Windows agrupa ticks del sistema (~15,6 ms en reposo); ciertos bucles de juego ganan fluidez con 0,5 ms.',
    'Windows coalesces system ticks (~15.6 ms idle); some game loops feel smoother at 0.5 ms.',
    'Lanza un helper oculto con NtSetTimerResolution(5000) y lo detiene al revertir; no sobrevive al reinicio.',
    'Starts a hidden helper calling NtSetTimerResolution(5000) and stops it on revert; not persistent across reboots.',
    'Temporizador del sistema (efecto temporal, más consumo energético).',
    'System timer (temporary effect, higher power draw).',
  ),
  'enable-mouse-raw-input': t(
    'Guía sobre Raw Input: lo solicita cada juego, no hay interruptor global.',
    'Raw Input guide: each game must request it; there is no global switch.',
    'Raw Input permite a una app leer el ratón sin procesamiento de Windows; los juegos lo activan en sus opciones.',
    'Raw Input lets an app read the mouse bypassing OS processing; games enable it in their own options.',
    'Solo muestra información; no cambia ningún valor del sistema.',
    'Informational only; changes no system value.',
    'Opciones internas de cada juego/aplicación.',
    'Each game/application\u2019s internal options.',
  ),
  'disable-keyboard-filter': t(
    'Guía: no existe un filtro de teclado global seguro que desactivar.',
    'Guide: there is no safe global keyboard filter to disable.',
    'Las Teclas de filtrado son una accesibilidad opcional; tocar servicios biométricos (WbioSrvc) no optimiza nada.',
    'Filter Keys is optional accessibility; touching biometric services (WbioSrvc) would not optimize anything.',
    'Solo muestra información; no modifica servicios ni valores.',
    'Informational only; changes no service or value.',
    'Opciones de accesibilidad de Teclas de filtrado.',
    'Filter Keys accessibility options.',
  ),

  // ─── TWEAKS ───────────────────────────────────────────────────────────────
  'animations': t(
    'Desactiva la animación de minimizar/maximizar (MinAnimate=0).',
    'Disables minimize/maximize animation (MinAnimate=0).',
    'MinAnimate controla la animación clásica de ventanas al minimizar o restaurar.',
    'MinAnimate controls the classic window animation when minimizing/restoring.',
    'Escribe MinAnimate=0 en WindowMetrics para respuesta visual instantánea.',
    'Writes MinAnimate=0 under WindowMetrics for instant visual response.',
    'Animaciones de ventana del perfil de usuario.',
    'Per-user window animations.',
  ),
  'transparency': t(
    'Desactiva efectos de transparencia/acrílico (EnableTransparency=0).',
    'Disables transparency/acrylic effects (EnableTransparency=0).',
    'La transparencia difumina fondo en barra de tareas, menús y paneles; cuesta composición de GPU.',
    'Transparency blurs backgrounds on taskbar, menus, and panels; costs GPU composition.',
    'Escribe EnableTransparency=0 en Themes\\Personalize; el cambio es visible al instante.',
    'Writes EnableTransparency=0 under Themes\\Personalize; visible immediately.',
    'Superficie compositora de DWM en todo el sistema.',
    'DWM composition surfaces system-wide.',
  ),
  'shadows': t(
    'Aplica el preajuste visual "Rendimiento mejor" (VisualFXSetting=2).',
    'Applies the "Best performance" visual preset (VisualFXSetting=2).',
    '"Rendimiento mejor" apaga sombras, animaciones y demás efectos decorativos de golpe.',
    '"Best performance" turns off shadows, animations, and other decorative effects in one go.',
    'Fija VisualFXSetting=2; quita sombras de ventana y el resto de efectos, no solo las sombras.',
    'Sets VisualFXSetting=2; removes window shadows and all other effects, not just shadows.',
    'Conjunto completo de efectos visuales de Explorer/DWM.',
    'The full Explorer/DWM visual-effects set.',
  ),
  'taskbar-icons': t(
    'Alinea la barra de tareas a la izquierda (Win11, TaskbarAl=0).',
    'Left-aligns the taskbar (Win11, TaskbarAl=0).',
    'Windows 11 centró los iconos de la barra de tareas por defecto.',
    'Windows 11 centers taskbar icons by default.',
    'Escribe TaskbarAl=0 en Explorer\\Advanced para recuperar el alineado clásico a la izquierda.',
    'Writes TaskbarAl=0 under Explorer\\Advanced to restore classic left alignment.',
    'Barra de tareas de Windows 11.',
    'The Windows 11 taskbar.',
  ),
  'notifications': t(
    'Desactiva el centro de notificaciones y los avisos emergentes por directiva.',
    'Disables Action Center and toast notifications via policy.',
    'DisableNotificationCenter oculta el centro de notificaciones y los toasts de apps.',
    'DisableNotificationCenter hides the notification center and app toasts.',
    'Crea la directiva Explorer DisableNotificationCenter=1 (requiere cerrar sesión o reiniciar).',
    'Creates the Explorer policy DisableNotificationCenter=1 (sign out or reboot needed).',
    'Centro de notificaciones y avisos de aplicaciones.',
    'Action Center and application notifications.',
  ),
  'show-file-extensions': t(
    'Muestra las extensiones de archivo conocidas (HideFileExt=0).',
    'Shows known file extensions (HideFileExt=0).',
    'Windows oculta ".exe", ".pdf", etc.; eso facilita que malware se disfrace con doble extensión.',
    'Windows hides ".exe", ".pdf", etc.; that helps malware disguise itself with double extensions.',
    'Escribe HideFileExt=0 y reinicia Explorer para aplicarlo al instante.',
    'Writes HideFileExt=0 and restarts Explorer to apply instantly.',
    'Vista de archivos de Explorador (todas las carpetas).',
    'File Explorer views across all folders.',
  ),
  'disable-thumbnails': t(
    'Sustituye miniaturas por iconos (IconsOnly=1).',
    'Replaces thumbnails with icons (IconsOnly=1).',
    'Generar miniaturas obliga a leer y renderizar imágenes/vídeos al abrir carpetas grandes.',
    'Generating thumbnails forces reading/rendering images/videos when opening large folders.',
    'Escribe IconsOnly=1 en Explorer\\Advanced y reinicia Explorer.',
    'Writes IconsOnly=1 under Explorer\\Advanced and restarts Explorer.',
    'Vistas de Explorador y caché de miniaturas.',
    'Explorer views and the thumbnail cache.',
  ),
  'disable-tooltips': t(
    'Desactiva la información emergente de archivos/carpetas (ShowInfoTip=0).',
    'Disables file/folder info tips (ShowInfoTip=0).',
    'Los tooltips de Explorer leen metadatos (tamaño, duración, miniatura) al pasar el cursor.',
    'Explorer tooltips read metadata (size, duration, thumbnail) on hover.',
    'Escribe ShowInfoTip=0 en Explorer\\Advanced.',
    'Writes ShowInfoTip=0 under Explorer\\Advanced.',
    'Tooltips de Explorador de archivos.',
    'File Explorer tooltips.',
  ),
  'disable-wallpaper-slideshow': t(
    'Detiene la rotación automática del fondo de escritorio (Interval=0).',
    'Stops automatic desktop wallpaper rotation (Interval=0).',
    'El slideshow cambia el wallpaper cada X minutos y despierta el disco/GPU para renderizarlo.',
    'Slideshow swaps wallpapers periodically, waking disk/GPU to render them.',
    'Fija Interval=0 en Desktop Slideshow para mantener el fondo fijo.',
    'Sets Interval=0 under Desktop Slideshow to keep a fixed wallpaper.',
    'Personalización del escritorio (slideshow activado desde Configuración).',
    'Desktop personalization (when slideshow is enabled in Settings).',
  ),
  'disable-system-sounds': t(
    'Cambia el esquema de sonido a "Sin sonidos".',
    'Switches the sound scheme to "No Sounds".',
    'El esquema .None silencia eventos del sistema: inicio, errores, dispositivos, alertas…',
    'The .None scheme mutes system events: startup, errors, devices, alerts…',
    'Escribe "(Default)"=.None en AppEvents\\Schemes.',
    'Writes "(Default)"=.None under AppEvents\\Schemes.',
    'Eventos de sonido de Windows (no afecta a música ni vídeos).',
    'Windows sound events (music/videos unaffected).',
  ),
  'show-hidden-files': t(
    'Muestra archivos y carpetas ocultos (Hidden=1).',
    'Shows hidden files and folders (Hidden=1).',
    'Windows oculta por defecto archivos de sistema y configuración para protegerlos de borrados accidentales.',
    'Windows hides system/config files by default to protect them from accidental deletion.',
    'Escribe Hidden=1 en Explorer\\Advanced.',
    'Writes Hidden=1 under Explorer\\Advanced.',
    'Visibilidad de elementos en Explorador.',
    'Item visibility in File Explorer.',
  ),
  'hide-task-view': t(
    'Oculta el botón de Vista de tareas (ShowTaskViewButton=0).',
    'Hides the Task View button (ShowTaskViewButton=0).',
    'Vista de tareas muestra escritorios virtuales y la línea de tiempo; su botón ocupa sitio en la barra.',
    'Task View shows virtual desktops and timeline; its button occupies taskbar space.',
    'Escribe ShowTaskViewButton=0 en Explorer\\Advanced.',
    'Writes ShowTaskViewButton=0 under Explorer\\Advanced.',
    'Botonera de la barra de tareas (Win+Tab sigue funcionando).',
    'Taskbar buttons (Win+Tab keeps working).',
  ),
  'disable-taskbar-search': t(
    'Oculta el cuadro/botón de búsqueda de la barra (SearchboxTaskbarMode=0).',
    'Hides the taskbar search box/button (SearchboxTaskbarMode=0).',
    'SearchboxTaskbarMode controla si la barra muestra búsqueda oculta, icono o caja completa.',
    'SearchboxTaskbarMode controls whether the taskbar shows hidden, icon-only, or full search.',
    'Fija SearchboxTaskbarMode=0; sigue buscando con Win+S.',
    'Sets SearchboxTaskbarMode=0; searching still works via Win+S.',
    'Elementos de búsqueda en la barra de tareas.',
    'Search elements on the taskbar.',
  ),
  'disable-lock-screen': t(
    'Salta la pantalla de bloqueo previa al login (NoLockScreen=1).',
    'Skips the lock screen before sign-in (NoLockScreen=1).',
    'La pantalla de bloqueo muestra imagen/hora y añade un paso antes de escribir tu contraseña.',
    'The lock screen shows imagery/time and adds a step before typing your password.',
    'Crea la directiva Personalization NoLockScreen=1.',
    'Creates the Personalization policy NoLockScreen=1.',
    'Flujo de inicio de sesión local (no sustituye a tu contraseña).',
    'Local sign-in flow (does not replace your password).',
  ),
  'disable-aero-peek': t(
    'Desactiva la vista previa del escritorio (DisablePreviewDesktop=1).',
    'Disables desktop peek (DisablePreviewDesktop=1).',
    'Peek muestra el escritorio al pasar el cursor sobre el borde derecho de la barra de tareas.',
    'Peek reveals the desktop when hovering the taskbar\u2019s right edge.',
    'Escribe DisablePreviewDesktop=1 en Explorer\\Advanced.',
    'Writes DisablePreviewDesktop=1 under Explorer\\Advanced.',
    'Botón "Mostrar el escritorio" y previsualizaciones Aero Peek.',
    'The "Show desktop" button and Aero Peek previews.',
  ),
  'disable-startup-sound': t(
    'Silencia el sonido de inicio de sesión de Windows.',
    'Mutes the Windows sign-in sound.',
    'WindowsLogon reproduce el jingle al iniciar sesión si el esquema lo define.',
    'WindowsLogon plays the sign-in jingle if the scheme defines one.',
    'Vacía "(Default)" en AppEvents\\.Default\\WindowsLogon.',
    'Empties "(Default)" under AppEvents\\.Default\\WindowsLogon.',
    'Evento de sonido de inicio de sesión.',
    'The sign-in sound event.',
  ),
  'disable-cast-notifications': t(
    'Impide notificaciones de proyección inalámbrica con pantalla bloqueada.',
    'Blocks wireless projection notifications while locked.',
    'La función Cast anuncia displays Miracast cercanos incluso con sesión bloqueada.',
    'Cast advertises nearby Miracast displays even on the locked session.',
    'Crea la clave Casting y fija AllowWhileLocked=0.',
    'Creates the Casting key and sets AllowWhileLocked=0.',
    'Anuncios Miracast/proyección en pantalla de bloqueo.',
    'Miracast/projection advertising on the lock screen.',
  ),
  'disable-background-apps': t(
    'Deshabilita globalmente las apps en segundo plano (GlobalUserDisabled=1).',
    'Globally disables background apps (GlobalUserDisabled=1).',
    'Las apps UWP pueden ejecutarse aunque no las abras, recibiendo push y gastando batería.',
    'UWP apps can run without being opened, receiving push data and draining battery.',
    'Escribe GlobalUserDisabled=1 en BackgroundAccessApplications.',
    'Writes GlobalUserDisabled=1 under BackgroundAccessApplications.',
    'Apps UWP/Microsoft Store (las apps Win32 clásicas siguen igual).',
    'UWP/Store apps (classic Win32 apps unaffected).',
  ),
  'disable-start-menu-suggestions': t(
    'Quita sugerencias promocionales del menú Inicio.',
    'Removes promotional suggestions from the Start menu.',
    'ContentDeliveryManager inserta sugerencias de apps y contenido patrocinado en Inicio.',
    'ContentDeliveryManager injects app suggestions and sponsored content into Start.',
    'Fija SystemPaneSuggestionsEnabled=0.',
    'Sets SystemPaneSuggestionsEnabled=0.',
    'Panel de sugerencias del menú Inicio.',
    'The Start menu suggestions pane.',
  ),

  // ─── POWERFUL ─────────────────────────────────────────────────────────────
  'power-plan': t(
    'Duplica y activa el plan "Rendimiento último" de Windows.',
    'Duplicates and activates the Windows "Ultimate Performance" plan.',
    'El plan Ultimate (e9a42b02…) elimina micro-latencias de estados de energía orientadas a portátiles.',
    'The Ultimate plan (e9a42b02…) removes laptop-oriented power-state micro-latencies.',
    'Duplica la plantilla oculta, activa el nuevo GUID y guarda ese GUID en %TEMP% para poder revertirlo.',
    'Duplicates the hidden template, activates the new GUID, and stashes that GUID in %TEMP% for reverting.',
    'Plan de energía activo (equipo de sobremesa recomendado; portátiles consumirán más).',
    'The active power plan (great on desktops; laptops will draw more power).',
  ),
  'gaming-mode': t(
    'Fuerza el Modo de juego de Windows (AllowAutoGameMode/AutoGameModeEnabled=1).',
    'Forces Windows Game Mode (AllowAutoGameMode/AutoGameModeEnabled=1).',
    'El Modo de juego da prioridad de planificador al juego en primer plano y pausa tareas secundarias.',
    'Game Mode gives the foreground game scheduler priority and defers secondary tasks.',
    'Escribe ambos valores a 1 en GameBar para garantizarlo aunque Configuración diga otra cosa.',
    'Writes both values to 1 under GameBar to enforce it even if Settings says otherwise.',
    'Prioridad del planificador y políticas de Xbox Game Bar.',
    'Scheduler priority and Xbox Game Bar policies.',
  ),
  'disable-services': t(
    'Deshabilita servicios prescindibles: MapsBroker y Fax.',
    'Disables dispensable services: MapsBroker and Fax.',
    'MapsBroker sincroniza datos del Conector de mapas y Fax gestiona faxes: nadie los usa en un PC gamer.',
    'MapsBroker syncs offline map data and Fax handles faxes: nobody uses them on a gaming rig.',
    'Detiene y deshabilita ambos servicios si existen.',
    'Stops and disables both services if they exist.',
    'Servicios MapsBroker y Fax (la impresión usa Spooler, no este ajuste).',
    'MapsBroker and Fax services (printing uses Spooler, untouched here).',
  ),
  'registry-cleanup': t(
    'Limpia historiales MRU: "Ejecutar" y rutas tecleadas de Explorer.',
    'Clears MRU histories: Run dialog and Explorer typed paths.',
    'RunMRU y TypedPaths guardan comandos y rutas recientes, útiles para huellas de privacidad.',
    'RunMRU and TypedPaths store recent commands/paths, a privacy footprint.',
    'Elimina las entradas de ambas claves; acción irreversible pero de riesgo nulo.',
    'Deletes entries from both keys; irreversible but zero-risk.',
    'Historiales del diálogo Ejecutar y de la barra de direcciones.',
    'Run-dialog and address-bar histories.',
  ),
  'memory-compression': t(
    'Desactiva la compresión de memoria (Disable-MMAgent).',
    'Disables memory compression (Disable-MMAgent).',
    'El almacén de compresión guarda páginas RAM comprimidas: ahorra memoria pero gasta CPU al comprimir/descomprimir.',
    'The compression store keeps compressed RAM pages: saves memory but burns CPU compressing/decompressing.',
    'Ejecuta Disable-MMAgent -MemoryCompression; con RAM abundante reduce carga de CPU.',
    'Runs Disable-MMAgent -MemoryCompression; with plenty of RAM it lowers CPU load.',
    'Administrador de memoria del kernel (recomendado ≥16 GB).',
    'Kernel memory manager (recommended with ≥16 GB).',
  ),
  'disable-hibernation': t(
    'Desactiva hibernación y borra hiberfil.sys (powercfg /hibernate off).',
    'Disables hibernation and deletes hiberfil.sys (powercfg /hibernate off).',
    'hiberfil.sys volca toda la RAM a disco para hibernar/Inicio rápido; suele ocupar ~40% de tu RAM.',
    'hiberfil.sys dumps full RAM to disk for hibernate/Fast Startup; usually ~40% of your RAM.',
    'Apaga hibernación vía powercfg y verifica HibernateEnabled=0 en el registro.',
    'Turns hibernation off via powercfg and verifies HibernateEnabled=0 in the registry.',
    'Archivo hiberfil.sys, hibernación e Inicio rápido.',
    'hiberfil.sys, hibernation, and Fast Startup.',
  ),
  'disable-fast-startup': t(
    'Desactiva el Inicio rápido (HiberbootEnabled=0).',
    'Disables Fast Startup (HiberbootEnabled=0).',
    'Fast Startup hiberne el kernel al "apagar": arranque más veloz pero drivers/actualizaciones quedan a medio aplicar.',
    'Fast Startup hibernates the kernel on shutdown: faster boots but drivers/updates half-applied.',
    'Escribe HiberbootEnabled=0 en Session Manager\\Power para apagados completos reales.',
    'Writes HiberbootEnabled=0 under Session Manager\\Power for true full shutdowns.',
    'Comportamiento de apagado/arranque (reinicio nunca lo usaba).',
    'Shutdown/boot behavior (Restart never used it anyway).',
  ),
  'enable-hags': t(
    'Activa la programación de GPU acelerada por hardware (HwSchMode=2).',
    'Enables Hardware-Accelerated GPU Scheduling (HwSchMode=2).',
    'HAGS deja que la propia GPU gestione sus colas en lugar del planificador por software de Windows.',
    'HAGS lets the GPU manage its own queues instead of Windows\u2019 software scheduler.',
    'Fija HwSchMode=2 en GraphicsDrivers (requiere reinicio y GPU compatible con WDDM 2.7+).',
    'Sets HwSchMode=2 under GraphicsDrivers (reboot required; needs a WDDM 2.7+ GPU).',
    'Colas de presentación de la GPU y latencia de frame.',
    'GPU presentation queues and frame latency.',
  ),
  'disable-bits': t(
    'Deshabilita BITS (Background Intelligent Transfer Service).',
    'Disables BITS (Background Intelligent Transfer Service).',
    'BITS transfiere datos en segundo plano con prioridad baja: actualizaciones, Store, telemetría de apps.',
    'BITS transfers data in the background at low priority: updates, Store, app telemetry.',
    'Deshabilita y detiene BITS; algunas descargas del sistema quedarán pendientes hasta revertirlo.',
    'Disables and stops BITS; some system downloads will pause until reverted.',
    'Servicio BITS y transferencias en segundo plano dependientes de él.',
    'BITS service and its dependent background transfers.',
  ),
  'disable-game-dvr': t(
    'Desactiva la grabación en segundo plano de Game DVR.',
    'Disables Game DVR background recording.',
    'Game DVR guarda buffer continuo de los últimos segundos para clips con Win+Alt+R, costando GPU constante.',
    'Game DVR keeps a rolling buffer for Win+Alt+R clips at a constant GPU cost.',
    'Escribe GameDVR_Enabled=0 en GameConfigStore.',
    'Writes GameDVR_Enabled=0 under GameConfigStore.',
    'Captura en segundo plano de juegos (capturas manuales siguen disponibles).',
    'Games\u2019 background capture (manual captures remain available).',
  ),
  'disable-power-throttling': t(
    'Desactiva Power Throttling (PowerThrottlingOff=1).',
    'Disables Power Throttling (PowerThrottlingOff=1).',
    'Power Throttling baja frecuencia a procesos marcados como segundo plano en CPUs Intel hybrid/skylake+.',
    'Power Throttling downclocks background-flagged processes on Intel Skylake+/hybrid CPUs.',
    'Crea la clave PowerThrottling y fija PowerThrottlingOff=1 para que ningún proceso se estrangule.',
    'Creates the PowerThrottling key and sets PowerThrottlingOff=1 so no process gets throttled.',
    'Estados de energía por proceso (mayor consumo, máxima constancia de clocks).',
    'Per-process power states (higher draw, steadier clocks).',
  ),
  'enable-msi-gpu': t(
    'Guía: MSI mode de la GPU se gestiona desde el driver/fabricante.',
    'Guide: GPU MSI mode is managed by the driver/vendor.',
    'MSI/MSI-X reduce latencia de interrupciones; forzarlo mal (registry MessageSignaledInterruptProperties) puede dejar la pantalla muerta.',
    'MSI/MSI-X reduces interrupt latency; forcing it blindly (MessageSignaledInterruptProperties) can black-screen your display.',
    'Solo lista tu GPU activa y explica el procedimiento seguro.',
    'Lists your active GPU and explains the safe procedure.',
    'Propiedades de interrupción del dispositivo gráfico.',
    'The graphics device\u2019s interrupt properties.',
  ),
  'disable-cpu-idle': t(
    'Prohíbe estados C bajos: mínimo procesador al 100% (PROCTHROTTLEMIN=100).',
    'Blocks low C-states: 100% minimum processor state (PROCTHROTTLEMIN=100).',
    'Los estados idle (C-states) ahorran energía pero tardan microsegundos en despertar, causando micro-stutter.',
    'Idle states save power but wake up slowly, causing micro-stutter.',
    'powercfg PROCTHROTTLEMIN=100 en corriente y reactiva el plan.',
    'Sets powercfg PROCTHROTTLEMIN=100 on AC and re-applies the plan.',
    'Estados de energía del procesador en AC (sube temperatura/consumo en reposo).',
    'AC processor power states (raises idle temps/power).',
  ),
  'enable-core-parking': t(
    'Desactiva el estacionamiento de núcleos (CPMINCORES=100).',
    'Disables core parking (CPMINCORES=100).',
    'Core parking apaga núcleos "sobrantes"; re-estacionarlos en picos de carga provoca tirón de frames.',
    'Core parking idles spare cores; unparking under load spikes causes frame hitching.',
    'Fija CPMINCORES=100 para que todos los núcleos estén siempre disponibles.',
    'Sets CPMINCORES=100 so every core stays available.',
    'Política de estacionamiento del plan activo.',
    'Active plan\u2019s parking policy.',
  ),
  'disable-memory-dumps': t(
    'Desactiva volcados de memoria ante BSOD (CrashDumpEnabled=0).',
    'Disables crash memory dumps (CrashDumpEnabled=0).',
    'Tras un BSOD Windows vuelca RAM completa a disco; en equipos con mucha RAM tarda minutos en reiniciar.',
    'After a BSOD Windows writes full RAM to disk; on high-RAM machines this stalls reboot for minutes.',
    'Escribe CrashDumpEnabled=0 en CrashControl.',
    'Writes CrashDumpEnabled=0 under CrashControl.',
    'Comportamiento post-BSOD (pierdes diagnósticos de fallos).',
    'Post-BSOD behavior (you lose crash diagnostics).',
  ),
  'enable-long-paths': t(
    'Habilita rutas Win32 largas (>260 caracteres).',
    'Enables long Win32 paths (>260 characters).',
    'Por compatibilidad histórica Windows limita las rutas a MAX_PATH=260; proyectos modernos (node_modules) la rebasan.',
    'For legacy reasons Windows caps paths at MAX_PATH=260; modern projects (node_modules) blow past it.',
    'Escribe LongPathsEnabled=1 en FileSystem.',
    'Writes LongPathsEnabled=1 under FileSystem.',
    'APIs de ficheros del sistema (apps deben declarar soporte longPathAware).',
    'System file APIs (apps must declare longPathAware support).',
  ),

  // ─── PRIVACY ──────────────────────────────────────────────────────────────
  'disable-advertising-id': t(
    'Desactiva tu ID publicitario de Windows.',
    'Disables your Windows Advertising ID.',
    'AdvertisingInfo genera un identificador único por usuario que las apps Store usan para anuncios personalizados.',
    'AdvertisingInfo issues a per-user ID that Store apps use for personalized ads.',
    'Fija Enabled=0 en AdvertisingInfo.',
    'Sets Enabled=0 under AdvertisingInfo.',
    'Identificador publicitario del perfil de usuario.',
    'Per-user advertising identifier.',
  ),
  'disable-tailored-experiences': t(
    'Desactiva experiencias personalizadas con datos de diagnóstico.',
    'Disables experiences tailored from diagnostic data.',
    'Windows usa tu telemetría para personalizar consejos, anuncios y sugerencias.',
    'Windows uses your telemetry to tailor tips, ads, and suggestions.',
    'Fija TailoredExperiencesWithDiagnosticDataEnabled=0.',
    'Sets TailoredExperiencesWithDiagnosticDataEnabled=0.',
    'Personalización basada en diagnósticos (tips y promos).',
    'Diagnostic-based personalization (tips/promos).',
  ),
  'disable-activity-history': t(
    'Impide publicar/subir el historial de actividades (Timeline).',
    'Blocks publishing/uploading activity history (Timeline).',
    'PublishUserActivities/UploadUserActivities alimentan la línea de tiempo de actividades entre dispositivos.',
    'PublishUserActivities/UploadUserActivities feed the cross-device Timeline.',
    'Ambas directivas a 0 en Policies\\…\\System.',
    'Sets both policies to 0 under Policies\\…\\System.',
    'Timeline local y sincronización de actividades a la nube.',
    'Local Timeline and cloud activity sync.',
  ),
  'disable-location-tracking': t(
    'Deniega globalmente el acceso a la ubicación.',
    'Globally denies location access.',
    'ConsentStore\\location controla si apps y sistema pueden geolocalizar el equipo.',
    'ConsentStore\\location gates whether apps/system can geolocate the PC.',
    'Escribe Value=Deny en el ConsentStore de ubicación.',
    'Writes Value=Deny to the location ConsentStore.',
    'Servicios de ubicación y permisos de apps de escritorio/UWP.',
    'Location services and desktop/UWP app permissions.',
  ),
  'disable-windows-feedback': t(
    'Silencia las peticiones de opiniones de Windows (NumberOfSIUFInPeriod=0).',
    'Silences Windows feedback requests (NumberOfSIUFInPeriod=0).',
    'Siuf programa cuántos avisos "¿Qué tal va tu experiencia?" aparecen por periodo.',
    'Siuf schedules how often "How\u2019s your experience?" prompts appear.',
    'Fija NumberOfSIUFInPeriod=0 en Siuf\\Rules.',
    'Sets NumberOfSIUFInPeriod=0 under Siuf\\Rules.',
    'Notificaciones de opinión/feedback del sistema.',
    'System feedback prompts.',
  ),
  'remove-onedrive': t(
    'Desinstala OneDrive de este usuario de Windows.',
    'Uninstalls OneDrive for this Windows user.',
    'OneDrive sincroniza Documentos/Escritorio con la nube; su desinstalación corta esa sincronización.',
    'OneDrive syncs Documents/Desktop to the cloud; uninstalling cuts that sync.',
    'Busca OneDriveSetup.exe (usuario o sistema), ejecuta /uninstall y tolera códigos de éxito conocidos.',
    'Locates OneDriveSetup.exe (per-user or system), runs /uninstall, tolerating known success codes.',
    'Cliente OneDrive local (respalda tus archivos antes de aplicar).',
    'The local OneDrive client (back up your files first).',
  ),
  'disable-cloud-content': t(
    'Bloquea contenido de consumo en la nube (DisableConsumerAccountStateContent).',
    'Blocks consumer cloud content (DisableConsumerAccountStateContent).',
    'Cloud Content entrega promos de Microsoft: sugerencias de apps, anuncios de Edge, bloqueos dinámicos…',
    'Cloud Content delivers Microsoft promos: app suggestions, Edge ads, dynamic lock screens…',
    'Fija DisableConsumerAccountStateContent=1 en CloudContent.',
    'Sets DisableConsumerAccountStateContent=1 under CloudContent.',
    'Entrega de contenido promocional desde servidores de Microsoft.',
    'Promotional content delivery from Microsoft servers.',
  ),
  'disable-app-suggestions': t(
    'Reduce las sugerencias de apps suscritas (SubscribedContent-338388=0).',
    'Reduces subscribed app suggestions (SubscribedContent-338388=0).',
    'El canal 338388 alimenta específicamente las sugerencias de aplicaciones de Inicio.',
    'Channel 338388 specifically feeds Start-menu app suggestions.',
    'Fija SubscribedContent-338388Enabled=0 en ContentDeliveryManager.',
    'Sets SubscribedContent-338388Enabled=0 under ContentDeliveryManager.',
    'Contenido suscrito del menú Inicio.',
    'Start menu subscribed content.',
  ),
  'disable-start-tracking': t(
    'Evita que Inicio registre el lanzamiento de apps (Start_TrackProgs=0).',
    'Stops Start tracking app launches (Start_TrackProgs=0).',
    'Start_TrackProgs alimenta listas de "usados frecuentemente" y el historial de programas.',
    'Start_TrackProgs feeds "most used" lists and program history.',
    'Escribe Start_TrackProgs=0 en Explorer\\Advanced.',
    'Writes Start_TrackProgs=0 under Explorer\\Advanced.',
    'Contadores de uso del menú Inicio y Jump Lists.',
    'Start usage counters and Jump Lists.',
  ),
  'disable-setting-sync': t(
    'Desactiva la sincronización de preferencias entre dispositivos (SyncPolicy=5).',
    'Disables preference sync between devices (SyncPolicy=5).',
    'SettingSync sube temas, contraseñas y preferencias a tu cuenta Microsoft.',
    'SettingSync uploads themes, passwords, and preferences to your Microsoft account.',
    'Fija SyncPolicy=5 (sin sync) en SettingSync.',
    'Sets SyncPolicy=5 (no sync) under SettingSync.',
    'Sincronización de temas/contraseñas vía cuenta Microsoft.',
    'Theme/password sync via Microsoft account.',
  ),
  'disable-input-personalization': t(
    'Bloquea la nube de personalización de escritura/tinta.',
    'Blocks typing/inking cloud personalization.',
    'InputPersonalization aprende de tu escritura y trazos para autocompletar diccionarios en la nube.',
    'InputPersonalization learns from typing/inking to feed cloud dictionaries.',
    'Fija RestrictImplicitInkCollection=1 y RestrictImplicitTextCollection=1.',
    'Sets RestrictImplicitInkCollection=1 and RestrictImplicitTextCollection=1.',
    'Diccionario predictivo y reconocimiento de escritura manual.',
    'Predictive dictionary and handwriting recognition.',
  ),
  'disable-handwriting-data': t(
    'Impide compartir datos de escritura manual (PreventHandwritingDataSharing).',
    'Blocks handwriting data sharing (PreventHandwritingDataSharing).',
    'TabletPC sharing envía muestras de tinta para mejorar el reconocimiento online.',
    'TabletPC sharing submits ink samples to improve online recognition.',
    'Crea la directiva TabletPC PreventHandwritingDataSharing=1.',
    'Creates the TabletPC policy PreventHandwritingDataSharing=1.',
    'Telemetría de tinta/escritura manual.',
    'Ink/handwriting telemetry.',
  ),
  'disable-speech-recognition': t(
    'Desactiva el reconocimiento de voz online (HasAccepted=0).',
    'Disables online speech recognition (HasAccepted=0).',
    'Con voz online, lo que dictas a Cortana/apps se procesa en servidores de Microsoft.',
    'With online speech, dictation to Cortana/apps is processed on Microsoft servers.',
    'Escribe HasAccepted=0 en OnlineSpeechPrivacy; la voz local del dispositivo sigue disponible.',
    'Writes HasAccepted=0 under OnlineSpeechPrivacy; on-device speech stays available.',
    'Dictado y voz basados en la nube.',
    'Cloud-based speech/dictation.',
  ),
  'disable-find-my-device': t(
    'Desactiva "Buscar mi dispositivo" (LocationSyncEnabled=0).',
    'Disables Find My Device (LocationSyncEnabled=0).',
    'FindMyDevice sincroniza periódicamente la ubicación del portátil con tu cuenta Microsoft.',
    'FindMyDevice periodically syncs your laptop\u2019s location to your Microsoft account.',
    'Fija LocationSyncEnabled=0 en Settings\\FindMyDevice.',
    'Sets LocationSyncEnabled=0 under Settings\\FindMyDevice.',
    'Reportes de ubicación del dispositivo a la nube.',
    'Device location reporting to the cloud.',
  ),
  'disable-contacts-access': t(
    'Deniega a las apps el acceso a contactos.',
    'Denies apps access to contacts.',
    'El ConsentStore contacts gateea qué apps pueden leer tu libreta de contactos.',
    'The contacts ConsentStore gates which apps can read your contact book.',
    'Escribe Value=Deny en CapabilityAccessManager\\ConsentStore\\contacts.',
    'Writes Value=Deny under CapabilityAccessManager\\ConsentStore\\contacts.',
    'Permiso global de lectura de contactos.',
    'The global contacts-read permission.',
  ),
  'disable-calendar-access': t(
    'Deniega a las apps el acceso al calendario.',
    'Denies apps calendar access.',
    'ConsentStore appointments controla la lectura de citas del calendario por parte de apps.',
    'The appointments ConsentStore controls apps reading your calendar entries.',
    'Escribe Value=Deny en el ConsentStore de appointments.',
    'Writes Value=Deny to the appointments ConsentStore.',
    'Permiso global de calendario.',
    'The global calendar permission.',
  ),
  'disable-camera-access': t(
    'Deniega a las apps el acceso a la cámara.',
    'Denies apps camera access.',
    'El ConsentStore webcam es el interruptor maestro de cámara para apps UWP/desktop.',
    'The webcam ConsentStore is the master camera switch for UWP/desktop apps.',
    'Escribe Value=Deny en el ConsentStore de webcam.',
    'Writes Value=Deny to the webcam ConsentStore.',
    'Permiso global de cámara (hardware intacto).',
    'The global camera permission (hardware untouched).',
  ),
  'disable-microphone-access': t(
    'Deniega a las apps el acceso al micrófono.',
    'Denies apps microphone access.',
    'El ConsentStore microphone corta el audio de entrada para todas las apps que dependen del permiso.',
    'The microphone ConsentStore cuts input audio for all permission-dependent apps.',
    'Escribe Value=Deny en el ConsentStore de microphone.',
    'Writes Value=Deny to the microphone ConsentStore.',
    'Permiso global de micrófono.',
    'The global microphone permission.',
  ),

  // ─── CATEGORY BATCH x10 EACH (2026-08) ────────────────────────────────
  // SYSTEM
  'disable-ceip-tasks': t(
    'Desactiva las tareas programadas de CEIP y Experiencia de aplicaciones.',
    'Disables CEIP and Application Experience scheduled tasks.',
    'El Programa de Mejora de la Experiencia ejecuta tareas periódicas (Consolidator, Compatibility Appraiser…) que recopilan y envían telemetría.',
    'The Customer Experience Improvement Program runs periodic tasks (Consolidator, Compatibility Appraiser…) that collect usage telemetry.',
    'Deshabilita Consolidator, UsbCeip, Microsoft Compatibility Appraiser y ProgramDataUpdater.',
    'Disables Consolidator, UsbCeip, Microsoft Compatibility Appraiser, and ProgramDataUpdater.',
    'Tareas programadas de diagnóstico del Programador de tareas.',
    'Diagnostic scheduled tasks in Task Scheduler.',
  ),
  'disable-last-access-time': t(
    'Deja de registrar la fecha de último acceso de cada archivo.',
    'Stops recording each file\u2019s last-access timestamp.',
    'Cada lectura de archivo actualiza su atributo de último acceso, generando escrituras extra.',
    'Every file read updates its last-access attribute, causing extra disk writes.',
    'Ejecuta fsutil behavior set disablelastaccess 1.',
    'Runs fsutil behavior set disablelastaccess 1.',
    'Metadatos NTFS y escrituras pequeñas en disco.',
    'NTFS metadata and small disk writes.',
  ),
  'disable-8dot3-names': t(
    'Deja de generar nombres cortos 8.3 (NOMBRE~1) en NTFS.',
    'Stops generating 8.3 short names (NAME~1) on NTFS.',
    'Por compatibilidad con DOS, Windows crea un segundo nombre corto por archivo: duplica entradas de directorio.',
    'For DOS compatibility Windows creates a second short name per file: doubling directory entries.',
    'Ejecuta fsutil behavior set disable8dot3 1; archivos existentes conservan sus nombres cortos.',
    'Runs fsutil behavior set disable8dot3 1; existing files keep their short names.',
    'Índices de nombres en carpetas grandes.',
    'Name indexes in large folders.',
  ),
  'disable-admin-shares': t(
    'Elimina las comparticiones administrativas C$ y ADMIN$.',
    'Removes the C$ and ADMIN$ administrative shares.',
    'Windows comparte cada unidad como C$ y Windows como ADMIN$ para gestión remota automática.',
    'Windows auto-shares every drive as C$ and Windows as ADMIN$ for remote management.',
    'Escribe AutoShareServer=0/AutoShareWks=0; aplican al reiniciar el servicio Servidor o el equipo.',
    'Writes AutoShareServer=0/AutoShareWks=0; applied when the Server service or PC restarts.',
    'Recursos compartidos ocultos del servidor LANMAN.',
    'Hidden LANMAN Server shares.',
  ),
  'disable-remote-assistance': t(
    'Desactiva las invitaciones de Asistencia remota.',
    'Disables Remote Assistance invitations.',
    'Permite que otro usuario vea/controle tu sesión mediante invitación; casi nadie la usa y es superficie de ataque.',
    'Lets another user view/control your session via invitation; rarely used and an attack surface.',
    'Fija fAllowToGetHelp=0 en Control\\Remote Assistance.',
    'Sets fAllowToGetHelp=0 under Control\\Remote Assistance.',
    'Canal de ayuda remota integrado (RDP/Quick Assist no cambian).',
    'Integrated remote-help channel (RDP/Quick Assist unaffected).',
  ),
  'disable-remote-desktop': t(
    'Bloquea las conexiones entrantes de Escritorio remoto.',
    'Blocks incoming Remote Desktop connections.',
    'RDP expone un servicio de login remoto; si no lo usas, cerrarlo elimina riesgo y procesos asociados.',
    'RDP exposes a remote login service; if unused, closing it removes risk and processes.',
    'Fija fDenyTSConnections=1 en Terminal Server.',
    'Sets fDenyTSConnections=1 under Terminal Server.',
    'Escritorio remoto entrante (conexiones salientes intactas).',
    'Incoming Remote Desktop (outbound unaffected).',
  ),
  'speedup-shutdown': t(
    'Apaga más rápido: menos espera de servicios y cierre automático de apps.',
    'Faster shutdowns: shorter service waits and automatic app closing.',
    'Windows espera hasta 5 s por servicio y pide confirmar apps con datos sin guardar antes de apagar.',
    'Windows waits up to 5 s per service and asks to confirm apps with unsaved data.',
    'Fija WaitToKillServiceTimeout=2000 ms y AutoEndTasks=1.',
    'Sets WaitToKillServiceTimeout=2000 ms and AutoEndTasks=1.',
    'Secuencia de apagado (guarda tu trabajo antes).',
    'Shutdown sequence (save your work first).',
  ),
  'no-auto-reboot-active': t(
    'Impide que Windows Update reinicie con tu sesión activa.',
    'Stops Windows Update rebooting while you are signed in.',
    'Sin esta directiva WU puede reiniciar aunque estés trabajando si la instalación lo pide.',
    'Without this policy WU may reboot mid-work when installation requires it.',
    'Aplica NoAutoRebootWithLoggedOnUsers=1 vía directiva AU.',
    'Applies NoAutoRebootWithLoggedOnUsers=1 via AU policy.',
    'Reinicios automáticos programados por Windows Update.',
    'Scheduled Windows Update automatic reboots.',
  ),
  'disable-driver-search': t(
    'Evita buscar controladores automáticamente en Windows Update.',
    'Stops automatically searching Windows Update for drivers.',
    'Las búsquedas automáticas instalan drivers genéricos y gastan ancho de banda/CPU en segundo plano.',
    'Automatic searches install generic drivers and burn background bandwidth/CPU.',
    'Fija SearchOrderConfig=0 en DriverSearching.',
    'Sets SearchOrderConfig=0 under DriverSearching.',
    'Instalación automática de controladores.',
    'Automatic driver installation.',
  ),
  // NETWORK
  'flush-arp-cache': t(
    'Vacía la tabla ARP local (mapeo IP↔MAC).',
    'Flushes the local ARP table (IP↔MAC map).',
    'La caché ARP guarda qué MAC corresponde a cada IP local; entradas obsoletas causan fallos intermitentes.',
    'The ARP cache stores which MAC maps to each local IP; stale entries cause intermittent glitches.',
    'Ejecuta arp -d * y verifica que la tabla pueda reconstruirse; acción repetible.',
    'Runs arp -d * and verifies the table can rebuild; repeatable action.',
    'Tabla de vecinos ARP del adaptador.',
    'The adapter\u2019s ARP neighbor table.',
  ),
  'disable-hotspot-service': t(
    'Desactiva el servicio del Punto de acceso móvil.',
    'Disables the Mobile Hotspot service.',
    'icssvc (Internet Connection Sharing) alimenta el hotspot Wi-Fi; si nunca compartes conexión, sobra.',
    'icssvc (Internet Connection Sharing) powers the Wi-Fi hotspot; useless if you never tether.',
    'Deshabilita icssvc si existe en tu instalación.',
    'Disables icssvc if present on your installation.',
    'Servicio ICS/hotspot (tu propia conexión no cambia).',
    'ICS/hotspot service (your own connectivity unchanged).',
  ),
  'require-network-level-auth': t(
    'Exige autenticación a nivel de red (NLA) para RDP.',
    'Requires Network Level Authentication for RDP.',
    'Sin NLA cualquiera abre una sesión pre-autenticación contra tu RDP: vector clásico de ataques.',
    'Without NLA anyone opens a pre-auth session against your RDP: a classic attack vector.',
    'Fija UserAuthentication=1 en WinStations\\RDP-Tcp.',
    'Sets UserAuthentication=1 under WinStations\\RDP-Tcp.',
    'Autenticación previa del Escritorio remoto.',
    'Remote Desktop pre-authentication layer.',
  ),
  'disable-wpad': t(
    'Desactiva WPAD, el descubrimiento automático de proxy.',
    'Disables WPAD automatic proxy discovery.',
    'WPAD pregunta por DHCP/DNS "¿hay proxy?"; un atacante puede suplantarlo y dirigir tu tráfico.',
    'WPAD asks DHCP/DNS "is there a proxy?"; attackers can spoof it to redirect traffic.',
    'Deshabilita el servicio WinHttpAutoProxySvc si existe.',
    'Disables the WinHttpAutoProxySvc service if present.',
    'Detección automática de proxy del stack HTTP.',
    'HTTP stack auto-proxy detection.',
  ),
  'disable-active-probing': t(
    'Detiene los sondeos NCSI hacia Microsoft.',
    'Stops NCSI probes toward Microsoft servers.',
    'NCSI consulta msftconnecttest.com constantemente para saber si hay internet; filtra datos y despierta la red.',
    'NCSI keeps querying msftconnecttest.com to check internet status; it leaks data and wakes the network.',
    'Fija EnableActiveProbing=0 bajo NlaSvc\\Parameters\\Internet.',
    'Sets EnableActiveProbing=0 under NlaSvc\\Parameters\\Internet.',
    'Comprobación de conectividad de red.',
    'Network connectivity checking.',
  ),
  'disable-peer-name-resolution': t(
    'Desactiva PNRP, la resolución de nombres P2P.',
    'Disables PNRP peer-name resolution.',
    'PNRP resuelve nombres descentralizados para apps colaborativas antiguas; hoy casi nada lo usa.',
    'PNRP resolves decentralized names for old collaboration apps; almost nothing uses it today.',
    'Deshabilita PNRPsvc si existe.',
    'Disables PNRPsvc if present.',
    'Servicios P2P de resolución de nombres.',
    'Peer-to-peer name-resolution services.',
  ),
  'restrict-point-and-print': t(
    'Solo administradores instalan drivers de impresoras de red.',
    'Only administrators install network printer drivers.',
    'Point and Print dejaba instalar drivers de impresora a cualquier usuario: vector PrintNightmare.',
    'Point and Print let any user install printer drivers: the PrintNightmare vector.',
    'Aplica RestrictDriverInstallationToAdministrators=1 por directiva.',
    'Applies RestrictDriverInstallationToAdministrators=1 via policy.',
    'Instalación de drivers Point and Print.',
    'Point and Print driver installation.',
  ),
  'disable-ssdp-discovery': t(
    'Silencia el tráfico de descubrimiento SSDP/UPnP.',
    'Silences SSDP/UPnP discovery traffic.',
    'SSDP difunde multicast buscando dispositivos: ruido, consumo y explotable para reflexión DDoS.',
    'SSDP broadcasts multicast looking for devices: noise, power draw, exploitable for DDoS reflection.',
    'Deshabilita el servicio SSDPSRV si existe.',
    'Disables the SSDPSRV service if present.',
    'Anuncios/descubrimiento UPnP en la LAN.',
    'LAN UPnP announcements/discovery.',
  ),
  'disable-upnp-device-host': t(
    'Desactiva el Host de dispositivo UPnP.',
    'Disables the UPnP Device Host service.',
    'upnphost publica este PC como dispositivo UPnP ante la red; innecesario fuera de DLNA específico.',
    'upnphost advertises this PC as a UPnP device; unnecessary outside specific DLNA setups.',
    'Deshabilita upnphost si existe (combina con SSDP).',
    'Disables upnphost if present (pairs with SSDP).',
    'Publicación UPnP de este equipo.',
    'This PC\u2019s UPnP publication.',
  ),
  'disable-snmp-trap': t(
    'Desactiva el receptor de traps SNMP.',
    'Disables the SNMP Trap receiver.',
    'SNMP Trap escucha alertas corporativas de red; en un PC doméstico es un servicio muerto.',
    'SNMP Trap listens for corporate network alerts; dead weight on a home PC.',
    'Deshabilita SNMPTRAP si existe.',
    'Disables SNMPTRAP if present.',
    'Recepción de eventos SNMP.',
    'SNMP event reception.',
  ),
  // INPUT
  'disable-filter-keys': t(
    'Desactiva el atajo de Teclas de filtrado (Shift largo).',
    'Disables the Filter Keys shortcut (held Shift).',
    'Mantener Shift 8 segundos abre Teclas de filtrado e ignora pulsaciones breves: interrumpe juegos y escritura rápida.',
    'Holding Shift 8 seconds triggers Filter Keys and ignores quick keystrokes: it interrupts gaming and fast typing.',
    'Escribe Flags=122 en Accessibility\\FilterKeys para quitar el atajo y sus avisos.',
    'Writes Flags=122 under Accessibility\\FilterKeys removing the shortcut and prompts.',
    'Accesibilidad de teclado del perfil de usuario.',
    'Per-user keyboard accessibility.',
  ),
  'disable-toggle-keys': t(
    'Desactiva el atajo de Teclas especiales de activación (BloqNum).',
    'Disables the Toggle Keys shortcut (NumLock tone).',
    'Pulsar BloqNum/Caps/BloqS con el atajo activo emite pitidos por cada pulsación.',
    'With the shortcut active, NumLock/Caps/Scroll emit a beep on every press.',
    'Escribe Flags=58 en Accessibility\\ToggleKeys.',
    'Writes Flags=58 under Accessibility\\ToggleKeys.',
    'Sonidos de bloqueo de teclas.',
    'Key-lock sounds.',
  ),
  'disable-touch-keyboard-autoinvoke': t(
    'Evita que el teclado táctil se abra solo en escritorio.',
    'Stops the touch keyboard auto-opening on desktops.',
    'Con pantallas táctiles, Windows puede desplegar el teclado en pantalla al tocar campos de texto en apps de escritorio.',
    'On touch screens, Windows may pop the on-screen keyboard when tapping text fields in desktop apps.',
    'Fija EnableDesktopModeAutoInvoke=0 en TabletTip\\1.7.',
    'Sets EnableDesktopModeAutoInvoke=0 under TabletTip\\1.7.',
    'Invocación automática del teclado táctil.',
    'Touch keyboard auto-invocation.',
  ),
  'disable-controller-gamebar-chord': t(
    'El botón Xbox del mando ya no abre Game Bar.',
    'The controller Xbox button no longer opens Game Bar.',
    'Con mandos conectados, pulsar el botón guía invoca la superposición de Xbox aunque estés en plena partida.',
    'With controllers connected, pressing the guide button invokes the Xbox overlay mid-match.',
    'Fija UseNexusForGameBarEnabled=0 en GameBar.',
    'Sets UseNexusForGameBarEnabled=0 under GameBar.',
    'Atajo Win+G desde mando (Win+G de teclado sigue funcionando).',
    'Controller-triggered Win+G (keyboard Win+G still works).',
  ),
  'disable-touchpad-edge-swipes': t(
    'Desactiva los gestos de bordes del touchpad preciso.',
    'Disables precision touchpad edge swipes.',
    'Los deslizamientos desde bordes abren Centro de actividades/Vista de tareas; provocan saltos accidentales al escribir.',
    'Edge swipes open Action Center/Task View; they cause accidental interruptions while typing.',
    'Escribe EdgeSwipeEnabled=0 en PrecisionTouchPad.',
    'Writes EdgeSwipeEnabled=0 under PrecisionTouchPad.',
    'Gestos de borde del touchpad compatible con Precision.',
    'Precision touchpad edge gestures.',
  ),
  'disable-touchpad-threefinger-slide': t(
    'Desactiva el gesto de tres dedos (cambio de ventanas).',
    'Disables the three-finger slide gesture.',
    'El slide de tres dedos alterna apps como Mission Control; toques accidentales cambian de ventana sin querer.',
    'Three-finger slides switch apps like Mission Control; accidental touches swap windows unexpectedly.',
    'Escribe ThreeFingerSlideEnabled=0 en PrecisionTouchPad.',
    'Writes ThreeFingerSlideEnabled=0 under PrecisionTouchPad.',
    'Gestos multitáctiles de navegación del touchpad.',
    'Touchpad multitouch navigation gestures.',
  ),
  'disable-windows-ink': t(
    'Desactiva el espacio de trabajo de Windows Ink.',
    'Disables the Windows Ink workspace.',
    'Ink carga servicios de lápiz/rasgos y su panel aunque no uses stylus.',
    'Ink loads pen/stroke services and its panel even without a stylus.',
    'Aplica AllowWindowsInkWorkspace=0 vía directiva HKLM.',
    'Applies AllowWindowsInkWorkspace=0 via HKLM policy.',
    'Panel de Ink y servicios de entrada de lápiz.',
    'Ink panel and pen-input services.',
  ),
  'numlock-on-boot': t(
    'Fuerza BloqNum activado al arrancar e iniciar sesión.',
    'Forces NumLock on at boot and sign-in.',
    'Muchos equipos arrancan con BloqNum apagado y hay que activarlo a mano cada vez.',
    'Many machines boot with NumLock off and you re-enable it every time.',
    'Escribe InitialKeyboardIndicators=2 en tu usuario y en .DEFAULT (aplica también a la pantalla de login).',
    'Writes InitialKeyboardIndicators=2 for your user and .DEFAULT (covers the login screen too).',
    'Estado inicial del teclado numérico.',
    'Numpad initial state.',
  ),
  'disable-hover-checkboxes': t(
    'Quita las casillas que aparecen al pasar el cursor en Explorer.',
    'Removes hover checkboxes in File Explorer.',
    'Al seleccionar archivos aparece una casilla bajo el cursor que provoca selecciones accidentales.',
    'Selecting files shows a checkbox under the cursor causing accidental selections.',
    'Escribe AutoCheckSelect=0 en Explorer\\Advanced.',
    'Writes AutoCheckSelect=0 under Explorer\\Advanced.',
    'Vista de elementos de Explorador de archivos.',
    'File Explorer item views.',
  ),
  'disable-tablet-input-service': t(
    'Desactiva el servicio de teclado táctil y escritura manual.',
    'Disables the Touch Keyboard and Handwriting service.',
    'TabletInputService alimenta el teclado en pantalla, el panel de escritura y la entrada de lápiz; sobra en PC de escritorio.',
    'TabletInputService powers the on-screen keyboard, handwriting panel, and pen input; useless on desktop towers.',
    'Deshabilita TabletInputService si existe (reactívalo si usas tabletas/lápices).',
    'Disables TabletInputService if present (re-enable if you use tablets/pens).',
    'Servicio de entrada táctil/manuscrita del sistema.',
    'System touch/handwriting input service.',
  ),
  // TWEAKS
  'delay-taskbar-thumbnails': t(
    'Retrasa las miniaturas emergentes de la barra de tareas.',
    'Delays taskbar thumbnail previews.',
    'Al pasar sobre iconos abiertos salen miniaturas casi al instante; el retardo evita parpadeos molestos.',
    'Hovering open icons pops thumbnails almost instantly; the delay avoids flickery previews.',
    'Fija ExtendedUIHoverTime=30000 ms (30 s) en Explorer\\Advanced.',
    'Sets ExtendedUIHoverTime=30000 ms under Explorer\\Advanced.',
    'Previsualizaciones emergentes de la barra.',
    'Taskbar hover previews.',
  ),
  'hide-start-recommended': t(
    'Oculta la sección Recomendados del menú Inicio.',
    'Hides the Start menu Recommended section.',
    'La zona inferior de Inicio muestra archivos recientes y promociones; muchos prefieren solo los anclajes.',
    'Start\u2019s lower zone shows recent files and promos; many prefer pins only.',
    'Aplica HideRecommendedSection=1 por directiva de usuario.',
    'Applies HideRecommendedSection=1 via user policy.',
    'Sección recomendados del Inicio (Windows 11 22H2+).',
    'Start\u2019s Recommended section (Windows 11 22H2+).',
  ),
  'disable-drag-full-window': t(
    'Muestra contornos en vez del contenido al arrastrar ventanas.',
    'Shows outlines instead of window contents while dragging.',
    'Redibujar toda la ventana mientras se arrastra cuesta composición GPU; el contorno es instantáneo.',
    'Repainting the whole window while dragging costs GPU composition; outlines are instant.',
    'Escribe DragFullWindows=0 en Control Panel\\Desktop.',
    'Writes DragFullWindows=0 under Control Panel\\Desktop.',
    'Renderizado durante arrastre de ventanas.',
    'Window-drag rendering.',
  ),
  'never-combine-taskbar-icons': t(
    'Nunca agrupa botones: siempre etiquetas completas en la barra.',
    'Never combines taskbar buttons: always full labels.',
    'Por defecto Windows agrupa instancias de una app en un icono; este ajuste muestra cada ventana individual.',
    'By default Windows groups app instances into one icon; this shows each window separately.',
    'Fija TaskbarGlomLevel=2 en Explorer\\Advanced.',
    'Sets TaskbarGlomLevel=2 under Explorer\\Advanced.',
    'Agrupación visual de la barra de tareas.',
    'Taskbar button grouping.',
  ),
  'disable-window-shake': t(
    'Desactiva "agitar ventana para minimizar el resto".',
    'Disables shake-to-minimize.',
    'Agarrar y agitar una ventana minimiza todas las demás; agitaciones accidentales ocultan tu escritorio.',
    'Grabbing and shaking a window minimizes all others; accidental shakes hide your workspace.',
    'Escribe DisableViewShake=1 en Explorer\\Advanced.',
    'Writes DisableViewShake=1 under Explorer\\Advanced.',
    'Gesto Aero Shake de gestión de ventanas.',
    'Aero Shake window-management gesture.',
  ),
  'disable-snap-layouts-flyout': t(
    'Quita el menú flotante de diseños del botón maximizar.',
    'Removes the snap-layouts flyout from the maximize button.',
    'Al pasar sobre maximizar aparece la rejilla de layouts; útil o ruido según cómo trabajes.',
    'Hovering maximize shows the layout grid; useful or noise depending on workflow.',
    'Escribe EnableSnapAssistFlyout=0 en Explorer\\Advanced.',
    'Writes EnableSnapAssistFlyout=0 under Explorer\\Advanced.',
    'Menú de Snap Layouts de Windows 11 (Win+flechas sigue).',
    'Windows 11 Snap Layouts menu (Win+arrows still work).',
  ),
  'disable-window-arrange-drag': t(
    'Arrastrar a los bordes ya no ajusta la ventana.',
    'Dragging to edges no longer snaps windows.',
    'El ajuste automático al arrastrar redimensiona ventanas sin querer cerca de bordes.',
    'Drag-to-snap resizes windows unintentionally near screen edges.',
    'Escribe WindowArrangementActive=0 en Control Panel\\Desktop.',
    'Writes WindowArrangementActive=0 under Control Panel\\Desktop.',
    'Snap por arrastre (atajos Win+flecha intactos).',
    'Drag-based snapping (Win+arrow shortcuts intact).',
  ),
  'disable-spotlight-wallpapers': t(
    'Cambia Spotlight de pantalla de bloqueo a imagen fija.',
    'Switches lock-screen Spotlight to a static image.',
    'Spotlight descarga imágenes y quizzes de Bing continuamente para renovar el fondo de bloqueo.',
    'Spotlight keeps downloading Bing images and quizzes to refresh the lock screen.',
    'Fija RotatingLockScreenEnabled=0 y RotatingLockScreenOverlayEnabled=0.',
    'Sets RotatingLockScreenEnabled=0 and RotatingLockScreenOverlayEnabled=0.',
    'Descargas y rotación de fondos de pantalla de bloqueo.',
    'Lock-screen wallpaper rotation/downloads.',
  ),
  'hide-copilot-button': t(
    'Elimina el botón de Copilot de la barra de tareas.',
    'Removes the Copilot button from the taskbar.',
    'Copilot integra un asistente en la nube anclado a la barra; consume recursos y no todos lo quieren ahí.',
    'Copilot pins a cloud assistant to the taskbar; it consumes resources and not everyone wants it.',
    'Aplica TurnOffWindowsCopilot=1 por directiva de usuario.',
    'Applies TurnOffWindowsCopilot=1 via user policy.',
    'Botón/superficie de Copilot en la barra de tareas.',
    'The Copilot taskbar surface.',
  ),
  // POWERFUL
  'optimize-thread-scheduling': t(
    'Ajusta Win32PrioritySeparation a quanta cortas con boost en primer plano.',
    'Sets Win32PrioritySeparation to short quanta with foreground boost.',
    'El valor por defecto reparte CPU entre todo; el ajuste 0x26 favorece la app activa con quantums más cortos y refuerzo.',
    'The default spreads CPU everywhere; value 0x26 favors the active app with shorter quanta and boost.',
    'Escribe Win32PrioritySeparation=38 (hex 26) en PriorityControl.',
    'Writes Win32PrioritySeparation=38 (hex 26) under PriorityControl.',
    'Planificador del kernel Windows (aplica tras reiniciar).',
    'The Windows kernel scheduler (applies after reboot).',
  ),
  'disable-svchost-split-threshold': t(
    'Agrupa servicios en procesos svchost compartidos.',
    'Groups services into shared svchost processes.',
    'Desde Win10 cada servicio corre aislado en su propio svchost: decenas de procesos y RAM duplicada; el umbral original los agrupa.',
    'Since Win10 each service runs isolated in its own svchost: dozens of processes and duplicated RAM; the legacy threshold groups them.',
    'Fija SvcHostSplitThresholdInKB=-1 (FFFFFFFF) en Control.',
    'Sets SvcHostSplitThresholdInKB=-1 (FFFFFFFF) under Control.',
    'Modelo de procesos de servicios (requiere reiniciar).',
    'Service process model (reboot required).',
  ),
  'optimize-ntfs-memory-usage': t(
    'Amplía la caché paginada dedicada al sistema de archivos NTFS.',
    'Enlarges the paged pool dedicated to NTFS.',
    'El nivel 1 (por defecto) es conservador; el nivel 2 asigna más memoria a metadatos MFT para acelerar operaciones con muchos ficheros.',
    'Level 1 is conservative; level 2 assigns more memory to MFT metadata, speeding up heavy file operations.',
    'Ejecuta fsutil behavior set memoryusage 2 (requiere reiniciar).',
    'Runs fsutil behavior set memoryusage 2 (reboot required).',
    'Caché de metadatos NTFS del sistema.',
    'System NTFS metadata cache.',
  ),
  'disable-modern-standby': t(
    'Sustituye Modern Standby (S0) por sueño clásico S3.',
    'Replaces Modern Standby (S0) with classic S3 sleep.',
    'Modern Standby mantiene el equipo semiactivo drenando batería y generando calor "dormido"; S3 apaga casi todo.',
    'Modern Standby keeps the PC semi-active draining battery while asleep; S3 powers almost everything down.',
    'Fija PlatformAoAcOverride=0 en Power (efectivo tras reiniciar).',
    'Sets PlatformAoAcOverride=0 under Power (effective after reboot).',
    'Estados de sueño del firmware/plataforma.',
    'Platform/firmware sleep states.',
  ),
  'disable-edge-startup-boost': t(
    'Desactiva la precarga de Edge al arrancar.',
    'Disables Microsoft Edge startup preloading.',
    'Startup Boost deja procesos de Edge residentes desde el encendido para abrirlo antes; gasta RAM/CPU aunque no navegues.',
    'Startup Boost keeps Edge processes resident from boot for faster launches; it burns RAM/CPU even if you never browse.',
    'Aplica StartupBoostEnabled=0 vía directiva HKLM de Edge.',
    'Applies StartupBoostEnabled=0 via the HKLM Edge policy.',
    'Procesos precargados de Microsoft Edge.',
    'Microsoft Edge preload processes.',
  ),
  'disable-automatic-maintenance': t(
    'Desactiva el Mantenimiento automático en reposo.',
    'Disables idle-time Automatic Maintenance.',
    'Windows agrupa defrag, diagnóstico y actualizaciones en ventanas de mantenimiento que despiertan el disco cuando "no haces nada".',
    'Windows bundles defrag, diagnostics, and updates into maintenance windows that wake your disk when you are "idle".',
    'Fija MaintenanceDisabled=1 en Schedule\\Maintenance.',
    'Sets MaintenanceDisabled=1 under Schedule\\Maintenance.',
    'Tareas agrupadas de mantenimiento programado.',
    'Scheduled maintenance task bundle.',
  ),
  'disable-app-readiness': t(
    'Desactiva el servicio App Readiness.',
    'Disables the App Readiness service.',
    'AppReadiness prepara apps de la Tienda en primeros inicios de sesión; en equipos ya configurados no hace nada útil.',
    'AppReadiness prepares Store apps at first sign-ins; on already-set-up machines it does nothing useful.',
    'Deshabilita AppReadiness si existe.',
    'Disables AppReadiness if present.',
    'Preparación/despliegue inicial de aplicaciones.',
    'Initial app deployment/preparation.',
  ),
  'disable-ssl-time-seeding': t(
    'Desactiva la siembra horaria SSL de W32Time.',
    'Disables W32Time SSL-based time seeding.',
    'Windows puede deducir la hora de handshakes TLS; algunos reportan saltos de reloj y es una fuente opaca.',
    'Windows can infer time from TLS handshakes; some report clock jumps from this opaque source.',
    'Fija UtilizeSslTimeData=0 en W32Time\\Config.',
    'Sets UtilizeSslTimeData=0 under W32Time\\Config.',
    'Fuente secundaria de sincronización horaria.',
    'A secondary time-sync source.',
  ),
  // PRIVACY
  'disable-clipboard-history': t(
    'Desactiva el historial del portapapeles local.',
    'Disables the local clipboard history.',
    'Con Win+V, Windows guarda un historial de todo lo que copias en un almacén persistente.',
    'With Win+V, Windows keeps a persistent history of everything you copy.',
    'Fija EnableClipboardHistory=0 en Software\\Microsoft\\Clipboard.',
    'Sets EnableClipboardHistory=0 under Software\\Microsoft\\Clipboard.',
    'Almacén local del portapapeles.',
    'The local clipboard store.',
  ),
  'disable-clipboard-cloud-sync': t(
    'Impide subir el portapapeles a la nube.',
    'Blocks clipboard upload to the cloud.',
    'Con sesión Microsoft, el contenido copiado puede sincronizarse entre dispositivos vía la nube.',
    'With a Microsoft account, copied content can sync between devices through the cloud.',
    'Fija CloudClipboardAutomaticUpload=0 en Software\\Microsoft\\Clipboard.',
    'Sets CloudClipboardAutomaticUpload=0 under Software\\Microsoft\\Clipboard.',
    'Portapapeles en la nube entre dispositivos.',
    'Cross-device cloud clipboard.',
  ),
  'deny-user-account-information': t(
    'Deniega a las apps el acceso a tu información de cuenta.',
    'Denies apps access to account information.',
    'El ConsentStore userAccountInformation regula qué apps leen tu nombre, foto y cuenta asociada.',
    'The userAccountInformation ConsentStore gates which apps read your name, picture, and account.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Permiso global de datos de cuenta.',
    'The global account-data permission.',
  ),
  'deny-documents-library': t(
    'Deniega a las apps la biblioteca Documentos.',
    'Denies apps the Documents library.',
    'El permiso documentsLibrary da a apps de tienda lectura/escritura sobre tus documentos sin diálogos.',
    'The documentsLibrary permission gives store apps silent read/write over your documents.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Permiso global de biblioteca Documentos.',
    'The global Documents-library permission.',
  ),
  'deny-pictures-library': t(
    'Deniega a las apps la biblioteca Imágenes.',
    'Denies apps the Pictures library.',
    'picturesLibrary permite a apps leer tus fotos completas sin preguntar carpeta a carpeta.',
    'picturesLibrary lets apps read all your photos without per-folder prompts.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Permiso global de biblioteca Imágenes.',
    'The global Pictures-library permission.',
  ),
  'deny-videos-library': t(
    'Deniega a las apps la biblioteca Vídeos.',
    'Denies apps the Videos library.',
    'videosLibrary expone tus vídeos a cualquier app autorizada en bloque, sin control fino.',
    'videosLibrary exposes your videos to any authorized app wholesale.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Permiso global de biblioteca Vídeos.',
    'The global Videos-library permission.',
  ),
  'deny-email-access': t(
    'Deniega a las apps el acceso a datos de correo.',
    'Denies apps access to email data.',
    'El ConsentStore email regula el acceso de apps UWP a cuentas/correo vinculadas al sistema.',
    'The email ConsentStore gates UWP app access to system-linked mail accounts.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Permiso global de email del sistema.',
    'The global system email permission.',
  ),
  'deny-radios-access': t(
    'Deniega a las apps el control de radios Wi-Fi/Bluetooth.',
    'Denies apps control of Wi-Fi/Bluetooth radios.',
    'El permiso radios permite a apps encender/apagar tus antenas sin pasar por Configuración.',
    'The radios permission lets apps toggle your antennas without going through Settings.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Control de dispositivos de radio del equipo.',
    'Device radio control.',
  ),
  'deny-human-presence': t(
    'Deniega a las apps los sensores de presencia humana.',
    'Denies apps human-presence sensor access.',
    'Los sensores de presencia (wake al acercarte, bloqueo al irte) exponen cuándo estás frente al equipo.',
    'Presence sensors (wake-on-approach, lock-on-leave) reveal when you are at the PC.',
    'Fija Value=Deny en su ConsentStore.',
    'Sets Value=Deny in its ConsentStore.',
    'Telemetría de presencia física ante el dispositivo.',
    'Physical presence telemetry.',
  ),
  'max-system-responsiveness': t(
    'Reserva 0% de CPU para tareas multimedia de fondo (SystemResponsiveness=0).',
    'Reserves zero percent CPU for background multimedia (SystemResponsiveness=0).',
    'MMCSS reserva por defecto un 20% de CPU para procesos multimedia de baja prioridad; en juegos compite con el render.',
    'By default MMCSS reserves 20% of CPU for low-priority background processes, competing with your game render.',
    'Fija SystemResponsiveness=0 en SystemProfile: el planificador deja de recortar CPU al juego.',
    'Sets SystemResponsiveness=0 under SystemProfile so the scheduler stops shaving CPU from the game.',
    'Perfil MMCSS del sistema (afecta a todo el equipo).',
    'The system-wide MMCSS profile.',
  ),
  'disable-memory-integrity': t(
    'Desactiva Integridad de memoria (HVCI), la ganancia de FPS más documentada en Valorant/Fortnite.',
    'Turns off Memory Integrity (HVCI): the most documented FPS win for Valorant/Fortnite.',
    'HVCI ejecuta la validación de drivers kernel dentro de un hipervisor ligero (VBS); ese aislamiento cuesta entre 5-10% de rendimiento según hardware.',
    'HVCI runs kernel-driver validation inside a lightweight hypervisor (VBS); that isolation costs roughly 5-10% of performance depending on hardware.',
    'Fija Enabled=0 bajo DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity (requiere reiniciar; se reactiva igual de fácil).',
    'Sets Enabled=0 under DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity (reboot required; just as easy to turn back on).',
    'Aislamiento de kernel basado en virtualización. REDUCE LA SEGURIDAD: actívalo solo si aceptas el riesgo y revierte después si prefieres protección.',
    'Virtualization-based kernel isolation. REDUCES SECURITY: enable only if you accept the risk and revert afterwards if you prefer protection.',
  ),
  'windowed-games-optimization': t(
    'Activa "Optimizaciones para juegos en ventana" (swap upgrade de Win11).',
    'Enables Windows 11 "Optimizations for windowed games" (swap upgrade).',
    'Los juegos DX10/11 en modo ventana/borderless usaban flip antiguo con más latencia; esta opción les da el modelo de presentación moderno.',
    'DX10/11 games in windowed/borderless used legacy flip with extra latency; this gives them the modern presentation model.',
    'Escribe SwapEffectUpgradeEnable=1 en DirectX\\UserGpuPreferences preservando el resto de ajustes.',
    'Writes SwapEffectUpgradeEnable=1 under DirectX\\UserGpuPreferences preserving other settings.',
    'Presentación de juegos en ventana/borderless (equivalente al toggle de Configuración, Win11 22H2+).',
    'Windowed/borderless game presentation (same as the Settings toggle, Win11 22H2+).',
  ),
  'disable-multiplane-overlay': t(
    'Desactiva MPO (Multi-Plane Overlay) del compositor.',
    'Disables the Multi-Plane Overlay compositor path.',
    'MPO deja que el hardware muestre planos directamente pero provoca parpadeos y micro-stutters en ciertas GPU/drivers (RDNA sobre todo).',
    'MPO lets hardware present planes directly but causes flicker and micro-stutters on some GPU/driver combos (RDNA especially).',
    'Fija OverlayTestMode=5 en Windows\\Dwm (requiere reiniciar).',
    'Sets OverlayTestMode=5 under Windows\\Dwm (reboot required).',
    'Ruta de presentación DWM (fix clásico de stutters/parpadeos reportado por AMD y NVIDIA users).',
    'DWM presentation path (classic stutter/flicker fix reported by AMD and NVIDIA users).',
  ),
  'static-pagefile': t(
    'Fija un pagefile estático de ~1,5× tu RAM en el disco del sistema.',
    'Configures a static pagefile of ~1.5× your RAM on the system drive.',
    'El pagefile automático crece/decrece dinámicamente; esas expansiones en plena partida causan stutters y fragmentación.',
    'The automatic pagefile grows/shrinks dynamically; those expansions mid-match cause stutters and fragmentation.',
    'Calcula 1,5× tu RAM física y escribe PagingFiles con tamaño inicial=máximo fijo.',
    'Computes 1.5× your physical RAM and writes PagingFiles with initial=max fixed size.',
    'Archivo de paginación del disco del sistema (requiere reinicio).',
    'System-drive pagefile (reboot required).',
  ),

  'uninstall-copilot': t(
    'Desinstala la app de Copilot de Microsoft (usuario y provisionado).',
    'Uninstalls the Microsoft Copilot app (user and provisioned).',
    'Copilot es el asistente de IA integrado anclado a la barra de tareas que ejecuta procesos en segundo plano.',
    'Copilot is the built-in AI assistant pinned to the taskbar that runs background processes.',
    'Elimina los paquetes AppX de Copilot para este usuario, todos los usuarios y su registro provisionado.',
    'Removes the Copilot AppX packages for this user, all users, and its provisioned registration.',
    'App de Copilot y sus procesos en segundo plano.',
    'The Copilot app and its background processes.',
  ),
  'uninstall-bing-search': t(
    'Desinstala la app de Búsqueda de Bing.',
    'Uninstalls the Bing Search app.',
    'Bing Search es la app que envuelve resultados web dentro de la búsqueda de Windows en Win11.',
    'Bing Search is the app wrapping web results inside Windows 11 search.',
    'Elimina el paquete AppX de Bing Search (usuario, todos los usuarios y provisionado).',
    'Removes the Bing Search AppX package (user, all users, and provisioned).',
    'Resultados web de búsqueda y su app contenedora.',
    'Search web results and their host app.',
  ),
  'disable-click-to-do': t(
    'Bloquea Click to Do (análisis IA de pantalla) por directiva.',
    'Blocks Click to Do (on-screen AI analysis) via policy.',
    'Click to Do analiza todo lo que ves en pantalla con IA local para sugerir acciones contextuales.',
    'Click to Do analyzes everything on screen with local AI to suggest contextual actions.',
    'Aplica DisableClickToDo=1 por directiva en HKCU y HKLM.',
    'Sets DisableClickToDo=1 via policy in both HKCU and HKLM.',
    'Funciones de análisis visual con IA del equipo.',
    'On-device visual AI analysis features.',
  ),
  'disable-paint-ai': t(
    'Desactiva Cocreator y Generador de imágenes de Paint.',
    'Disables Paint Cocreator and Image Generator.',
    'Paint integra IA generativa (Cocreator colaborativo y generación de imágenes por texto) que descarga modelos locales.',
    'Paint ships generative AI (collaborative Cocreator and text-to-image generation) that downloads local models.',
    'Aplica las directivas DisableCocreator=1 y DisableImageGenerator=1.',
    'Sets DisableCocreator=1 and DisableImageGenerator=1 policies.',
    'Funciones IA de la app Paint.',
    'Paint app AI features.',
  ),

  // ─── NEW BATCH (2026-08) ──────────────────────────────────────────────
  'disable-widgets': t(
    'Desactiva el panel de Widgets y su botón en la barra de tareas.',
    'Disables the Widgets panel and its taskbar button.',
    'Widgets es el panel de noticias, clima y contenido patrocinado integrado en Windows 11 que consulta la web constantemente.',
    'Widgets is the news/weather/sponsored-content panel built into Windows 11 that constantly fetches web content.',
    'Aplica la directiva Dsh AllowNewsAndInterests=0 y oculta el botón TaskbarDa de la barra.',
    'Applies the Dsh AllowNewsAndInterests=0 policy and hides the TaskbarDa button on the taskbar.',
    'Directiva de Widgets del sistema y botón de la barra de tareas.',
    'System Widgets policy and the taskbar button.',
  ),
  'disable-recall': t(
    'Bloquea Recall y el análisis de actividad con IA vía directiva.',
    'Blocks Recall and AI activity analysis via policy.',
    'Recall captura pantallas periódicamente y las analiza con IA para crear una línea temporal buscable de todo lo que hiciste.',
    'Recall periodically captures your screen and uses AI to build a searchable timeline of everything you did.',
    'Fija DisableAIDataAnalysis=1 en la directiva WindowsAI del usuario para impedir las instantáneas y su análisis.',
    'Sets DisableAIDataAnalysis=1 under the user\u2019s WindowsAI policy to block snapshots and their analysis.',
    'Características de IA/Recall del equipo local (por directiva de usuario).',
    'Local AI/Recall features (per-user policy).',
  ),
  'disable-netbios': t(
    'Desactiva NetBIOS sobre TCP/IP en todas las interfaces.',
    'Disables NetBIOS over TCP/IP on every interface.',
    'NetBIOS es un protocolo de nombres/sesiones de los años 80; hoy solo sirve a equipos antiguos y a atacantes que enumeran la red.',
    'NetBIOS is an 1980s naming/session protocol; today only legacy machines and network attackers benefit from it.',
    'Escribe NetbiosOptions=2 en cada interfaz bajo NetBT\\Parameters\\Interfaces (0 = usar DHCP por defecto).',
    'Writes NetbiosOptions=2 under every NetBT\\Parameters\\Interfaces key (0 = use the DHCP default).',
    'Enlaces NetBT de todos los adaptadores de red.',
    'NetBT bindings of every network adapter.',
  ),
  'disable-smb1': t(
    'Desactiva el protocolo obsoleto SMBv1 en el servidor del sistema.',
    'Disables the deprecated SMBv1 protocol system-wide on the server side.',
    'SMBv1 es el protocolo de compartición explotado por WannaCry/NotPetya; Windows 10/11 ya no lo necesitan.',
    'SMBv1 is the share protocol exploited by WannaCry/NotPetya; Windows 10/11 no longer need it.',
    'Usa Set-SmbServerConfiguration -EnableSMB1Protocol $false; los recursos modernos (SMB2/3) siguen funcionando igual.',
    'Runs Set-SmbServerConfiguration -EnableSMB1Protocol $false; modern SMB2/3 shares keep working unchanged.',
    'Servidor SMB del equipo (compartir archivos/impresoras).',
    'This PC\u2019s SMB server (file/printer sharing).',
  ),
  'show-seconds-clock': t(
    'Muestra los segundos en el reloj de la barra de tareas.',
    'Shows seconds in the taskbar clock.',
    'Por defecto Windows solo muestra horas y minutos; esta opción añade los segundos (Win10 1607+/Win11).',
    'Windows shows only hours and minutes by default; this adds seconds (Win10 1607+/Win11).',
    'Escribe ShowSecondsInSystemClock=1 en Explorer\\Advanced.',
    'Writes ShowSecondsInSystemClock=1 under Explorer\\Advanced.',
    'Renderizado del reloj del sistema (coste mínimo de CPU).',
    'System clock rendering (negligible CPU cost).',
  ),
  'hide-meet-now': t(
    'Oculta el icono "Reunir ahora" (Meet Now) de la barra.',
    'Hides the Meet Now icon from the taskbar.',
    'Meet Now integra llamadas de Skype en la bandeja del sistema en Windows 10; muchos lo consideran bloatware.',
    'Meet Now embeds Skype calling into the Windows 10 system tray; many consider it bloatware.',
    'Escribe ShowMeetNow=0 en Explorer\\Advanced.',
    'Writes ShowMeetNow=0 under Explorer\\Advanced.',
    'Iconos de la bandeja/barra de tareas.',
    'Tray/taskbar icons.',
  ),
  'disable-fullscreen-optimizations': t(
    'Desactiva las optimizaciones de pantalla completa para juegos.',
    'Disables fullscreen optimizations for games globally.',
    'FSO redirige los juegos exclusivos a través del compositor DWM; reduce alt+tab pero puede añadir latencia de frame.',
    'FSO routes exclusive-fullscreen games through the DWM compositor; it eases alt-tabbing but can add frame latency.',
    'Fija GameDVR_FSOBehavior=1 en GameConfigStore para forzar modo exclusivo real (equivale al checkbox por-juego).',
    'Sets GameDVR_FSOBehavior=1 under GameConfigStore to force true exclusive fullscreen (same as the per-game checkbox).',
    'Presentación fullscreen de juegos (aplica a títulos nuevos tras cerrarlos).',
    'Game fullscreen presentation (applies to newly launched titles).',
  ),
  'disable-welcome-experience': t(
    'Desactiva la página "Dale más vida a tu dispositivo" (bienvenida).',
    'Disables the "Get even more out of Windows" welcome experience.',
    'El canal SubscribedContent-310093 alimenta la experiencia de bienvenida que ofrece configurar Office, Game Pass, etc.',
    'Channel SubscribedContent-310093 feeds the first-run experience pushing Office, Game Pass, and friends.',
    'Fija SubscribedContent-310093Enabled=0 en ContentDeliveryManager.',
    'Sets SubscribedContent-310093Enabled=0 under ContentDeliveryManager.',
    'Pantallas promocionales post-actualización/primer arranque.',
    'Promotional screens after updates or first sign-in.',
  ),
};
