import fs from 'node:fs';
const p = 'src/lib/optimization-commands.ts';
let s = fs.readFileSync(p, 'utf8');
const oldEs = 'REDUCE LA SEGURIDAD: desactiva el aislamiento de kernel (HVCI). Ganas FPS reales, pero un exploit de kernel tendrá más fácil comprometer el sistema. No lo uses si manejas datos sensibles.';
const newEs = 'REDUCE LA SEGURIDAD: desactiva el aislamiento de kernel (HVCI). Ganas FPS reales, pero un exploit de kernel tendrá más fácil comprometer el sistema. IMPORTANTE: requiere reiniciar ANTES de abrir juegos; aplicarlo y entrar directo a Valorant puede impedir que arranque (Vanguard revalida en el arranque). No lo uses si manejas datos sensibles.';
const oldEn = 'REDUCES SECURITY: turns off kernel isolation (HVCI). You gain real FPS, but a kernel exploit has an easier time compromising the system. Avoid if you handle sensitive data.';
const newEn = 'REDUCES SECURITY: turns off kernel isolation (HVCI). You gain real FPS, but a kernel exploit has an easier time compromising the system. IMPORTANT: reboot BEFORE launching games; applying it and launching Valorant directly may prevent it from starting (Vanguard revalidates at boot). Avoid if you handle sensitive data.';
if (!s.includes(oldEs)) throw new Error('warning ES not found');
s = s.replace(oldEs, newEs);
s = s.replace(oldEn, newEn);
fs.writeFileSync(p, s);
console.log('HVCI warning actualizado');
