namespace CAO.UI;

/// <summary>
/// Typed UI strings (spec 84): es-ES and en-US are first-class. No raw text
/// scattered through pages; adding a language means adding one dictionary.
/// All strings flow through Localizer.Get(key); technical identifiers are never translated.
/// </summary>
public static class Localizer
{
    public static IReadOnlyList<string> SupportedLanguages { get; } = ["es-ES", "en-US"];

    private static readonly Dictionary<string, string> Spanish = new()
    {
        ["app.title"] = "CA-O",
        ["app.subtitle"] = "Plataforma de rendimiento para Windows",
        ["nav.dashboard"] = "Panel",
        ["nav.analyze"] = "Analizar",
        ["nav.optimize"] = "Optimizar",
        ["nav.gaming"] = "Gaming",
        ["nav.diagnostics"] = "Diagnóstico",
        ["nav.benchmark"] = "Benchmark",
        ["nav.restore"] = "Restaurar",
        ["nav.history"] = "Historial",
        ["nav.settings"] = "Ajustes",
        ["dashboard.analyze"] = "Analizar sistema",
        ["dashboard.analyzing"] = "Analizando…",
        ["dashboard.lastAnalysis"] = "Último análisis",
        ["dashboard.never"] = "nunca",
        ["dashboard.recommended"] = "Recomendados",
        ["dashboard.optional"] = "Opcionales",
        ["dashboard.experimental"] = "Experimentales",
        ["dashboard.securitySensitive"] = "Seguridad sensible",
        ["dashboard.notApplicable"] = "No aplicables",
        ["dashboard.health"] = "Salud del sistema",
        ["dashboard.findings"] = "Hallazgos",
        ["dashboard.noClaims"] = "Sin promesas numéricas: solo mediciones.",
        ["analyze.run"] = "Ejecutar diagnósticos",
        ["analyze.diagnosticsFirst"] = "Diagnósticos primero",
        ["analyze.diagnosticsFirstMessage"] = "Cada área se mide antes de recomendar cualquier cambio. Nada aquí modifica el sistema.",
        ["optimize.applyRecommended"] = "Aplicar recomendados",
        ["optimize.apply"] = "Aplicar",
        ["optimize.revert"] = "Revertir",
        ["optimize.preview"] = "Ver cambios",
        ["optimize.expertWarning"] = "Modo Expert activo: los cambios experimentales y sensibles a seguridad quedan visibles pero siguen requiriendo confirmación.",
        ["benchmark.baseline"] = "Medir línea base",
        ["benchmark.after"] = "Medir tras cambio",
        ["benchmark.running"] = "Midiendo…",
        ["restore.pointNote"] = "CA-O crea snapshots propios antes de cada cambio; el punto de restauración de Windows se solicita una vez por sesión cuando el sistema lo permite.",
        ["settings.expertMode"] = "Modo Expert",
        ["settings.theme"] = "Tema",
        ["settings.language"] = "Idioma",
        ["settings.serviceCheck"] = "Comprobar servicio privilegiado",
        ["common.workloadDependent"] = "Depende de la carga de trabajo",
        ["common.noClaims"] = "Sin promesas numéricas: solo mediciones.",
        ["common.connected"] = "Conectado",
        ["common.disconnected"] = "No disponible",
        ["common.healthy"] = "Correcto",
        ["common.warning"] = "Atención",
        ["common.attention"] = "Requiere atención",
        ["common.systemStatus"] = "Estado del sistema",
        ["common.serviceStatus"] = "Servicio",
        ["common.lastScan"] = "Último análisis",
        ["common.requiresReboot"] = "requiere reinicio",
        ["common.cancel"] = "Cancelar",
        ["analyze.title"] = "Analizar sistema",
        ["analyze.runFull"] = "Ejecutar análisis completo",
        ["analyze.lastAnalysis"] = "Último análisis: hace {0} días",
        ["analyze.stale"] = "Se recomienda ejecutar un análisis nuevo",
        ["analyze.staleMessage"] = "Para mantener recomendaciones actualizadas, ejecuta un nuevo análisis aproximadamente una vez por semana.",
        ["analyze.fresh"] = "Análisis actualizado",
        ["analyze.freshMessage"] = "El análisis es reciente. No es necesario volver a analizar aún.",
        ["analyze.veryStale"] = "Este análisis es antiguo. Ejecuta un análisis nuevo antes de optimizar.",
        ["analyze.veryStaleMessage"] = "El análisis tiene más de 14 días. Ejecuta un análisis nuevo para obtener recomendaciones precisas.",
        ["analyze.gameChanged"] = "Se detectaron cambios en los juegos instalados.",
        ["analyze.gameChangedMessage"] = "Se recomienda ejecutar un nuevo análisis.",
        ["analyze.noAnalysis"] = "No hay un análisis guardado.",
        ["analyze.noAnalysisMessage"] = "Ejecuta un análisis para generar recomendaciones.",
        ["analyze.completed"] = "Análisis completo — {0} módulos",
        ["analyze.failed"] = "Análisis fallido",
        ["analyze.cancelled"] = "Análisis cancelado",
        ["analyze.gameHint"] = "También se recomienda volver a analizar después de instalar un juego nuevo.",
        ["optimize.title"] = "Optimizar",
        ["optimize.filterAll"] = "Todas",
        ["optimize.filterRecommended"] = "Recomendadas",
        ["optimize.filterOptional"] = "Opcionales",
        ["optimize.filterExperimental"] = "Experimentales",
        ["optimize.noResults"] = "Sin optimizaciones",
        ["optimize.noRecommended"] = "Sin optimizaciones recomendadas",
        ["optimize.noOptional"] = "Sin optimizaciones opcionales",
        ["optimize.noExperimental"] = "Sin optimizaciones experimentales",
        ["optimize.expertRequired"] = "Las optimizaciones experimentales requieren Modo Expert.",
        ["optimize.lockedOptional"] = "Opcional — requiere Modo Expert para aplicar (ver Ajustes).",
        ["optimize.lockedExperimental"] = "Experimental — solo en Modo Expert, puede ser inestable.",
        ["optimize.lockedSecurity"] = "Sensible a seguridad — requiere Modo Expert y confirmación.",
        ["optimize.lockedAntiCheat"] = "Bloqueado por anti-cheat — con candado para no romper juegos.",
        ["optimize.lockedIncompatible"] = "No compatible con este hardware/sistema.",
        ["dns.applied"] = "DNS aplicado correctamente.",
        ["dns.primary"] = "Primario",
        ["dns.secondary"] = "Secundario",
        ["dns.verified"] = "Verificado.",
        ["dns.failed"] = "No fue posible aplicar DNS.",
        ["dns.adapter"] = "Adaptador",
        ["bucket.recommended"] = "Recomendado",
        ["bucket.optional"] = "Opcional",
        ["bucket.experimental"] = "Experimental",
        ["bucket.securitySensitive"] = "Seguridad sensible",
        ["bucket.notApplicable"] = "No aplicable",
        ["bucket.blocked"] = "Bloqueado",
        ["risk.low"] = "Bajo",
        ["risk.moderate"] = "Moderado",
        ["risk.high"] = "Alto",
        ["evidence.official"] = "Oficial",
        ["evidence.vendor"] = "Vendor",
        ["evidence.benchmark"] = "Benchmark",
        ["evidence.empirical"] = "Empírico",
        ["evidence.heuristic"] = "Heurístico",
        ["evidence.unknown"] = "Desconocido",
        // Analyze page extra
        ["analyze.subtitle"] = "Escaneo completo: CPU, GPU, memoria, disco, velocidades, red, seguridad, drivers, térmica e input. Nada aquí modifica el sistema.",
        ["analyze.progress"] = "Progreso del análisis",
        ["analyze.cpuPlaceholder"] = "Ejecuta análisis para medir CPU",
        ["analyze.gpuPlaceholder"] = "Ejecuta análisis para medir GPU",
        ["analyze.ramPlaceholder"] = "Ejecuta análisis para medir RAM",
        ["analyze.driversDesc"] = "Lista drivers con código de problema, sin firma o detenidos. Si no detecta nada, no hay problemas.",
        ["analyze.dpcTitle"] = "Latencia DPC/ISR",
        ["analyze.dpcDesc"] = "Mide % Tiempo DPC e Interrupción. Alto = audio entrecortado, micro-stutter, input lag. Se auto-ejecuta con el análisis.",
        ["analyze.sample5s"] = "Muestrear 5 s",
        ["analyze.gamingBlockedTitle"] = "Gaming — optimizaciones bloqueadas",
        ["analyze.gamingBlockedDesc"] = "Anti-cheat detectado bloquea cambios que reducen seguridad. Con candado en Optimizar.",
        ["analyze.gamingPlaceholder"] = "Ejecuta análisis para detectar anti-cheat y juegos",
        ["analyze.applyDns"] = "Aplicar mejor DNS detectado",
        ["analyze.cpu"] = "CPU",
        ["analyze.gpu"] = "GPU",
        ["analyze.memory"] = "Memoria",
        ["analyze.storage"] = "Almacenamiento",
        ["analyze.network"] = "Red",
        ["analyze.security"] = "Seguridad",
        ["analyze.drivers"] = "Drivers",
        ["analyze.thermal"] = "Térmico",
        // Dashboard extra
        ["dashboard.systemIntelligence"] = "System Intelligence  ·  Diagnóstico primero, cambios transaccionales, benchmark honesto.",
        ["dashboard.bucketsDesc"] = "Buckets analyze-first: solo lo medido genera recomendación. Experimental y Security Sensitive requieren Modo Expert.",
        ["dashboard.directApply"] = "Aplicación directa disponible",
        ["dashboard.requiresReview"] = "Requiere revisión",
        ["dashboard.expertOnly"] = "Solo en Modo Expert",
        ["dashboard.explicitConfirm"] = "Confirmación explícita",
        ["dashboard.nextStep"] = "Próximo paso recomendado",
        ["dashboard.whyState"] = "¿Por qué este estado?",
        ["dashboard.noFindingsDesc"] = "No se detectaron problemas. Ejecute un análisis completo para refrescar.",
        ["dashboard.goOptimize"] = "Revisar en Optimizar →",
        // Diagnostics
        ["diagnostics.title"] = "Diagnóstico",
        ["diagnostics.subtitle"] = "Módulos con estado actual, métricas brutas, interpretación y confianza. Sin telemetría externa.",
        ["diagnostics.runAll"] = "Ejecutar diagnósticos completos",
        ["diagnostics.input"] = "Entrada",
        ["diagnostics.thermal"] = "Térmico",
        ["diagnostics.performance"] = "Rendimiento actual",
        // Benchmark
        ["benchmark.title"] = "Benchmark",
        ["benchmark.flow"] = "Flujo guiado: Paso 1 Crear línea base → Paso 2 Aplicar optimización → Paso 3 Medir después → Paso 4 Comparar → Paso 5 Veredicto",
        ["benchmark.baselineTitle"] = "Línea base",
        ["benchmark.compare"] = "Comparación A/B",
        // Gaming
        ["gaming.vendorTech"] = "Tecnologías del fabricante",
        ["gaming.scan"] = "Escanear sistema gaming",
        // Restore/History/Settings
        ["restore.title"] = "Restaurar",
        ["restore.subtitle"] = "Centro de restauración — snapshots por TransactionId, no por OptimizationId. Cada reversión se verifica exactamente.",
        ["restore.recentOps"] = "Últimas operaciones",
        ["restore.recentDesc"] = "Cada transacción muestra TransactionId, riesgo, estado y reversión.",
        ["history.subtitle"] = "Timeline auditable con TransactionId, operación, verificación y cadena hash. La corrupción genera alerta explícita.",
        ["history.noHistory"] = "Sin historial aún",
        ["settings.subtitle"] = "Organizados por categorías. Sin listas infinitas.",
        ["settings.policy"] = "Política de optimización",
        ["settings.policyDesc"] = "Expert expone Security Sensitive y Experimental solo para revisión avanzada. Nunca aplica sin confirmación ni snapshot.",
        ["settings.philosophy"] = "CA-O — Filosofía",
        ["settings.philosophyDesc"] = "Diagnóstico primero → recomendaciones por evidencia → transacción con snapshot y verificación → benchmark honesto → rollback exacto. Sin promesas numéricas.",
        ["common.details"] = "Detalles",
        ["common.apply"] = "Aplicar",
        ["common.revert"] = "Revertir",
    };

    private static readonly Dictionary<string, string> English = new()
    {
        ["app.title"] = "CA-O",
        ["app.subtitle"] = "Windows performance platform",
        ["nav.dashboard"] = "Dashboard",
        ["nav.analyze"] = "Analyze",
        ["nav.optimize"] = "Optimize",
        ["nav.gaming"] = "Gaming",
        ["nav.diagnostics"] = "Diagnostics",
        ["nav.benchmark"] = "Benchmark",
        ["nav.restore"] = "Restore",
        ["nav.history"] = "History",
        ["nav.settings"] = "Settings",
        ["dashboard.analyze"] = "Analyze system",
        ["dashboard.analyzing"] = "Analyzing…",
        ["dashboard.lastAnalysis"] = "Last analysis",
        ["dashboard.never"] = "never",
        ["dashboard.recommended"] = "Recommended",
        ["dashboard.optional"] = "Optional",
        ["dashboard.experimental"] = "Experimental",
        ["dashboard.securitySensitive"] = "Security sensitive",
        ["dashboard.notApplicable"] = "Not applicable",
        ["dashboard.health"] = "System health",
        ["dashboard.findings"] = "Findings",
        ["dashboard.noClaims"] = "No numeric promises: measurements only.",
        ["analyze.run"] = "Run diagnostics",
        ["analyze.diagnosticsFirst"] = "Diagnostics first",
        ["analyze.diagnosticsFirstMessage"] = "Each area is measured before any change is recommended. Nothing here modifies the system.",
        ["optimize.applyRecommended"] = "Apply recommended",
        ["optimize.apply"] = "Apply",
        ["optimize.revert"] = "Revert",
        ["optimize.preview"] = "Preview changes",
        ["optimize.expertWarning"] = "Expert mode active: experimental and security-sensitive changes become visible but still require confirmation.",
        ["benchmark.baseline"] = "Measure baseline",
        ["benchmark.after"] = "Measure after change",
        ["benchmark.running"] = "Measuring…",
        ["restore.pointNote"] = "CA-O takes its own snapshots before every change; a Windows restore point is requested once per session when the system allows it.",
        ["settings.expertMode"] = "Expert mode",
        ["settings.theme"] = "Theme",
        ["settings.language"] = "Language",
        ["settings.serviceCheck"] = "Check privileged service",
        ["common.workloadDependent"] = "Workload dependent",
        ["common.noClaims"] = "No numeric promises: measurements only.",
        ["common.connected"] = "Connected",
        ["common.disconnected"] = "Unavailable",
        ["common.healthy"] = "Healthy",
        ["common.warning"] = "Warning",
        ["common.attention"] = "Attention required",
        ["common.systemStatus"] = "System status",
        ["common.serviceStatus"] = "Service",
        ["common.lastScan"] = "Last scan",
        ["common.requiresReboot"] = "requires reboot",
        ["common.cancel"] = "Cancel",
        ["analyze.title"] = "Analyze system",
        ["analyze.runFull"] = "Run full analysis",
        ["analyze.lastAnalysis"] = "Last analysis: {0} days ago",
        ["analyze.stale"] = "A new analysis is recommended",
        ["analyze.staleMessage"] = "To keep recommendations up to date, run a new analysis about once a week.",
        ["analyze.fresh"] = "Analysis up to date",
        ["analyze.freshMessage"] = "Analysis is recent. No need to re-run yet.",
        ["analyze.veryStale"] = "This analysis is outdated. Run a new analysis before optimizing.",
        ["analyze.veryStaleMessage"] = "Analysis is older than 14 days. Run a new analysis for accurate recommendations.",
        ["analyze.gameChanged"] = "Changes in installed games detected.",
        ["analyze.gameChangedMessage"] = "A new analysis is recommended.",
        ["analyze.noAnalysis"] = "No saved analysis.",
        ["analyze.noAnalysisMessage"] = "Run an analysis to generate recommendations.",
        ["analyze.completed"] = "Analysis complete — {0} modules",
        ["analyze.failed"] = "Analysis failed",
        ["analyze.cancelled"] = "Analysis cancelled",
        ["analyze.gameHint"] = "Also recommended to re-analyze after installing a new game.",
        ["optimize.title"] = "Optimize",
        ["optimize.filterAll"] = "All",
        ["optimize.filterRecommended"] = "Recommended",
        ["optimize.filterOptional"] = "Optional",
        ["optimize.filterExperimental"] = "Experimental",
        ["optimize.noResults"] = "No optimizations",
        ["optimize.noRecommended"] = "No recommended optimizations",
        ["optimize.noOptional"] = "No optional optimizations",
        ["optimize.noExperimental"] = "No experimental optimizations",
        ["optimize.expertRequired"] = "Experimental optimizations require Expert mode.",
        ["optimize.lockedOptional"] = "Optional — requires Expert mode (see Settings).",
        ["optimize.lockedExperimental"] = "Experimental — Expert mode only, may be unstable.",
        ["optimize.lockedSecurity"] = "Security sensitive — requires Expert mode and confirmation.",
        ["optimize.lockedAntiCheat"] = "Blocked by anti-cheat — locked to avoid breaking games.",
        ["optimize.lockedIncompatible"] = "Not compatible with this hardware/system.",
        ["dns.applied"] = "DNS applied successfully.",
        ["dns.primary"] = "Primary",
        ["dns.secondary"] = "Secondary",
        ["dns.verified"] = "Verified.",
        ["dns.failed"] = "Could not apply DNS.",
        ["dns.adapter"] = "Adapter",
        ["bucket.recommended"] = "Recommended",
        ["bucket.optional"] = "Optional",
        ["bucket.experimental"] = "Experimental",
        ["bucket.securitySensitive"] = "Security sensitive",
        ["bucket.notApplicable"] = "Not applicable",
        ["bucket.blocked"] = "Blocked",
        ["risk.low"] = "Low",
        ["risk.moderate"] = "Moderate",
        ["risk.high"] = "High",
        ["evidence.official"] = "Official",
        ["evidence.vendor"] = "Vendor",
        ["evidence.benchmark"] = "Benchmark",
        ["evidence.empirical"] = "Empirical",
        ["evidence.heuristic"] = "Heuristic",
        ["evidence.unknown"] = "Unknown",
        ["analyze.subtitle"] = "Full scan: CPU, GPU, memory, disk, speeds, network, security, drivers, thermal and input. Nothing here modifies the system.",
        ["analyze.progress"] = "Analysis progress",
        ["analyze.cpuPlaceholder"] = "Run analysis to measure CPU",
        ["analyze.gpuPlaceholder"] = "Run analysis to measure GPU",
        ["analyze.ramPlaceholder"] = "Run analysis to measure RAM",
        ["analyze.driversDesc"] = "Lists drivers with problem code, unsigned or stopped. If nothing is found, there are no issues.",
        ["analyze.dpcTitle"] = "DPC/ISR latency",
        ["analyze.dpcDesc"] = "Measures % DPC Time and Interrupt. High = choppy audio, micro-stutter, input lag. Auto-runs with analysis.",
        ["analyze.sample5s"] = "Sample 5 s",
        ["analyze.gamingBlockedTitle"] = "Gaming — blocked optimizations",
        ["analyze.gamingBlockedDesc"] = "Anti-cheat detected blocks changes that reduce security. Locked in Optimize.",
        ["analyze.gamingPlaceholder"] = "Run analysis to detect anti-cheat and games",
        ["analyze.applyDns"] = "Apply best detected DNS",
        ["analyze.cpu"] = "CPU",
        ["analyze.gpu"] = "GPU",
        ["analyze.memory"] = "Memory",
        ["analyze.storage"] = "Storage",
        ["analyze.network"] = "Network",
        ["analyze.security"] = "Security",
        ["analyze.drivers"] = "Drivers",
        ["analyze.thermal"] = "Thermal",
        ["dashboard.systemIntelligence"] = "System Intelligence  ·  Diagnostics first, transactional changes, honest benchmark.",
        ["dashboard.bucketsDesc"] = "Analyze-first buckets: only measured generates recommendation. Experimental and Security Sensitive require Expert mode.",
        ["dashboard.directApply"] = "Direct application available",
        ["dashboard.requiresReview"] = "Requires review",
        ["dashboard.expertOnly"] = "Expert mode only",
        ["dashboard.explicitConfirm"] = "Explicit confirmation",
        ["dashboard.nextStep"] = "Recommended next step",
        ["dashboard.whyState"] = "Why this state?",
        ["dashboard.noFindingsDesc"] = "No issues detected. Run a full analysis to refresh.",
        ["dashboard.goOptimize"] = "Review in Optimize →",
        ["diagnostics.title"] = "Diagnostics",
        ["diagnostics.subtitle"] = "Modules with current state, raw metrics, interpretation and confidence. No external telemetry.",
        ["diagnostics.runAll"] = "Run full diagnostics",
        ["diagnostics.input"] = "Input",
        ["diagnostics.thermal"] = "Thermal",
        ["diagnostics.performance"] = "Current performance",
        ["benchmark.title"] = "Benchmark",
        ["benchmark.flow"] = "Guided flow: Step 1 Create baseline → Step 2 Apply optimization → Step 3 Measure after → Step 4 Compare → Step 5 Verdict",
        ["benchmark.baselineTitle"] = "Baseline",
        ["benchmark.compare"] = "A/B Comparison",
        ["gaming.vendorTech"] = "Vendor technologies",
        ["gaming.scan"] = "Scan gaming system",
        ["restore.title"] = "Restore",
        ["restore.subtitle"] = "Restore center — snapshots by TransactionId, not by OptimizationId. Each revert is verified exactly.",
        ["restore.recentOps"] = "Recent operations",
        ["restore.recentDesc"] = "Each transaction shows TransactionId, risk, state and revert.",
        ["history.subtitle"] = "Auditable timeline with TransactionId, operation, verification and hash chain. Corruption triggers explicit alert.",
        ["history.noHistory"] = "No history yet",
        ["settings.subtitle"] = "Organized by categories. No endless lists.",
        ["settings.policy"] = "Optimization policy",
        ["settings.policyDesc"] = "Expert exposes Security Sensitive and Experimental only for advanced review. Never applies without confirmation or snapshot.",
        ["settings.philosophy"] = "CA-O — Philosophy",
        ["settings.philosophyDesc"] = "Diagnostics first → evidence-based recommendations → transaction with snapshot and verification → honest benchmark → exact rollback. No numeric promises.",
        ["common.details"] = "Details",
        ["common.apply"] = "Apply",
        ["common.revert"] = "Revert",
    };

    private static Dictionary<string, string> Current { get; set; } = Spanish;

    public static void SetLanguage(string language)
    {
        Current = language.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? English : Spanish;
    }

    public static string Get(string key) =>
        Current.TryGetValue(key, out var value) ? value : key;

    public static string Format(string key, params object[] args)
    {
        var template = Get(key);
        try { return string.Format(template, args); } catch { return template; }
    }

    public static string GetBucketLabel(CAO.Shared.RecommendationBucket bucket) => bucket switch
    {
        CAO.Shared.RecommendationBucket.Recommended => Get("bucket.recommended"),
        CAO.Shared.RecommendationBucket.Optional => Get("bucket.optional"),
        CAO.Shared.RecommendationBucket.Experimental => Get("bucket.experimental"),
        CAO.Shared.RecommendationBucket.SecuritySensitive => Get("bucket.securitySensitive"),
        CAO.Shared.RecommendationBucket.NotApplicable => Get("bucket.notApplicable"),
        _ => bucket.ToString()
    };

    public static string GetRiskLabel(CAO.Shared.RiskLevel risk) => risk.ToString().ToLowerInvariant() switch
    {
        "low" => Get("risk.low"),
        "moderate" => Get("risk.moderate"),
        "high" => Get("risk.high"),
        _ => risk.ToString()
    };

    public static string GetEvidenceLabel(CAO.Shared.EvidenceLevel ev) => ev.ToString().ToLowerInvariant() switch
    {
        "official" => Get("evidence.official"),
        "vendor" => Get("evidence.vendor"),
        "benchmark" => Get("evidence.benchmark"),
        "empirical" => Get("evidence.empirical"),
        "heuristic" => Get("evidence.heuristic"),
        _ => Get("evidence.unknown")
    };

    public static string GetSecurityLabel(CAO.Shared.SecurityImpact imp) => imp.ToString();
}
